// Package generator writes a Go SDK package from a service's definitions, the
// way Pandora's generator-go-sdk writes go-azure-sdk: it reads nothing but the
// definitions, and every decision it makes about the API was already made by
// the importer.
//
// One package per server (BaseItemDto is everywhere, so per-tag packages would
// all import one another), laid out by tag in file names:
//
//	client.go                          Client and New
//	client_test.go                     the canned server the tests share
//	doc.go                             the package documentation
//	<tag>_method_<operation>.go        one per operation: the method, its
//	                                   <Name>OperationResponse, its
//	                                   <Name>OperationOptions, and for list
//	                                   operations a <Name>Complete pager
//	<tag>_method_<operation>_test.go   the operation's test (tests.go)
//	<tag>_model_<model>.go             one per model
//	<tag>_constants.go                 the tag's enums
//
// Requests go through the hand-written base client, lib/client.
package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/katbyte/sonarr-mcp/internal/pandorest/definitions"
)

// Header starts every generated file; it is also how a stale generated file
// is recognised for removal.
const Header = "// Code generated by internal/pandorest; DO NOT EDIT.\n"

// ClientImport is the base client's import path.
const ClientImport = "github.com/katbyte/sonarr-mcp/lib/client"

// Options says where a service's package goes and where it came from.
type Options struct {
	// Dir is the package directory.
	Dir string
	// Definitions is the definitions directory, named in the package doc.
	Definitions string
}

// Generate writes the package and removes generated files it no longer
// produces. It returns the number of files written.
func Generate(svc *definitions.Service, opts Options) (int, error) {
	files, err := Render(svc, opts)
	if err != nil {
		return 0, err
	}
	if err := os.MkdirAll(opts.Dir, 0o755); err != nil { //nolint:gosec // generated source, world-readable is right
		return 0, err
	}
	if err := removeStale(opts.Dir, files); err != nil {
		return 0, err
	}
	for _, name := range sortedKeys(files) {
		path := filepath.Join(opts.Dir, name)
		if old, err := os.ReadFile(path); err == nil && bytes.Equal(old, files[name]) { //nolint:gosec // a file in the package directory
			continue
		}
		if err := os.WriteFile(path, files[name], 0o644); err != nil { //nolint:gosec // generated source, world-readable is right
			return 0, err
		}
	}

	return len(files), nil
}

// Render produces every file of the package, formatted, by name.
func Render(svc *definitions.Service, opts Options) (map[string][]byte, error) {
	if err := definitions.Validate(svc); err != nil {
		return nil, err
	}
	g, err := newGen(svc, opts)
	if err != nil {
		return nil, err
	}

	sources := map[string]string{
		"client.go":      g.clientFile(),
		"client_test.go": g.testHelpersFile(),
		"doc.go":         g.docFile(),
	}
	add := func(name, src string) error {
		if _, ok := sources[name]; ok {
			return fmt.Errorf("two declarations would both be written to %s", name)
		}
		sources[name] = src
		return nil
	}
	for gi := range svc.Groups {
		grp := &svc.Groups[gi]
		prefix := fileStem(grp.Name)
		if len(grp.Constants) > 0 {
			if err := add(prefix+"_constants.go", g.constantsFile(grp)); err != nil {
				return nil, err
			}
		}
		for mi := range grp.Models {
			m := &grp.Models[mi]
			if err := add(fileName(prefix, "model", m.Name), g.modelFile(m)); err != nil {
				return nil, err
			}
		}
		for oi := range grp.Operations {
			o := &grp.Operations[oi]
			name := fileName(prefix, "method", o.Name)
			if err := add(name, g.methodFile(o)); err != nil {
				return nil, err
			}
			if err := add(strings.TrimSuffix(name, ".go")+"_test.go", g.testFile(o)); err != nil {
				return nil, err
			}
		}
	}
	if err := g.checkIdentifiers(); err != nil {
		return nil, err
	}

	files := make(map[string][]byte, len(sources))
	for name, src := range sources {
		out, err := format.Source([]byte(src))
		if err != nil {
			return nil, fmt.Errorf("%s: generated code does not parse: %w\n%s", name, err, numbered(src))
		}
		files[name] = out
	}

	return files, nil
}

// removeStale deletes generated Go files, tests included, in dir that are not
// about to be written. Hand-written files (no generated header) are left
// alone.
func removeStale(dir string, keep map[string][]byte) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || filepath.Ext(name) != ".go" || keep[name] != nil {
			continue
		}
		path := filepath.Join(dir, name)
		src, err := os.ReadFile(path) //nolint:gosec // a file in the package directory
		if err != nil {
			return err
		}
		if bytes.HasPrefix(src, []byte(Header)) {
			if err := os.Remove(path); err != nil {
				return err
			}
		}
	}

	return nil
}

// buildSuffixes are file name endings the go tool reads as build constraints
// (_test, and _<GOOS> or _<GOARCH> as the last element).
var buildSuffixes = func() map[string]bool {
	m := map[string]bool{}
	for s := range strings.FieldsSeq("test aix android darwin dragonfly freebsd hurd illumos ios js linux nacl netbsd openbsd plan9 solaris wasip1 windows zos " +
		"386 amd64 amd64p32 arm armbe arm64 arm64be loong64 mips mipsle mips64 mips64le mips64p32 mips64p32le ppc ppc64 ppc64le riscv riscv64 s390 s390x sparc sparc64 wasm") {
		m[s] = true
	}

	return m
}()

// fileStem lower-cases a name for use in a file name.
func fileStem(name string) string { return strings.ToLower(name) }

// fileName is <group>_<kind>_<name>.go, with the name kept from reading as a
// build constraint.
func fileName(prefix, kind, name string) string {
	stem := fileStem(name)
	if buildSuffixes[stem] {
		stem += "type"
	}

	return prefix + "_" + kind + "_" + stem + ".go"
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	slices.Sort(keys)

	return keys
}

func numbered(src string) string {
	var b strings.Builder
	for i, line := range strings.Split(src, "\n") {
		fmt.Fprintf(&b, "%4d  %s\n", i+1, line)
	}

	return b.String()
}
