// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PostAutoTaggingOperationResponse is the result of PostAutoTagging.
type PostAutoTaggingOperationResponse struct {
	HttpResponse *http.Response
	Model        *AutoTaggingResource
}

// PostAutoTagging calls POST /api/v3/autotagging.
func (c Client) PostAutoTagging(ctx context.Context, input AutoTaggingResource) (result PostAutoTaggingOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusCreated,
		},
		HttpMethod: http.MethodPost,
		Path:       "/api/v3/autotagging",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model AutoTaggingResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
