// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetAutoTaggingOperationResponse is the result of GetAutoTagging.
type GetAutoTaggingOperationResponse struct {
	HttpResponse *http.Response
	Model        []AutoTaggingResource
}

// GetAutoTagging calls GET /api/v3/autotagging.
func (c Client) GetAutoTagging(ctx context.Context) (result GetAutoTaggingOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/autotagging",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
