// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// AutoTaggingSpecificationSchema is the "AutoTaggingSpecificationSchema" schema.
type AutoTaggingSpecificationSchema struct {
	Fields             []Field `json:"fields,omitzero"`
	Id                 int     `json:"id,omitempty"`
	Implementation     string  `json:"implementation,omitempty"`
	ImplementationName string  `json:"implementationName,omitempty"`
	Name               string  `json:"name,omitempty"`
	Negate             *bool   `json:"negate,omitempty"`
	Required           *bool   `json:"required,omitempty"`
}
