// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetAutoTaggingByIdOperationResponse is the result of GetAutoTaggingById.
type GetAutoTaggingByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *AutoTaggingResource
}

// GetAutoTaggingById calls GET /api/v3/autotagging/{id}.
func (c Client) GetAutoTaggingById(ctx context.Context, id int) (result GetAutoTaggingByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/api/v3/autotagging/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model AutoTaggingResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
