// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// AutoTaggingResource is the "AutoTaggingResource" schema.
type AutoTaggingResource struct {
	Id                      int                              `json:"id,omitempty"`
	Name                    string                           `json:"name,omitempty"`
	RemoveTagsAutomatically *bool                            `json:"removeTagsAutomatically,omitempty"`
	Specifications          []AutoTaggingSpecificationSchema `json:"specifications,omitzero"`
	Tags                    []int                            `json:"tags,omitzero"`
}
