// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetAutoTaggingSchemaOperationResponse is the result of GetAutoTaggingSchema.
type GetAutoTaggingSchemaOperationResponse struct {
	HttpResponse *http.Response
	Model        []AutoTaggingSpecificationSchema
}

// GetAutoTaggingSchema calls GET /api/v3/autotagging/schema.
func (c Client) GetAutoTaggingSchema(ctx context.Context) (result GetAutoTaggingSchemaOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/autotagging/schema",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
