// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PostSystemBackupRestoreByIdOperationResponse is the result of PostSystemBackupRestoreById.
type PostSystemBackupRestoreByIdOperationResponse struct {
	HttpResponse *http.Response
}

// PostSystemBackupRestoreById calls POST /api/v3/system/backup/restore/{id}.
func (c Client) PostSystemBackupRestoreById(ctx context.Context, id int) (result PostSystemBackupRestoreByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodPost,
		Path:       fmt.Sprintf("/api/v3/system/backup/restore/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
