// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// BackupResource is the "BackupResource" schema.
type BackupResource struct {
	Id   int        `json:"id,omitempty"`
	Name string     `json:"name,omitempty"`
	Path string     `json:"path,omitempty"`
	Size int64      `json:"size,omitempty"`
	Time string     `json:"time,omitempty"`
	Type BackupType `json:"type,omitempty"`
}
