// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PostSystemBackupRestoreUploadOperationResponse is the result of PostSystemBackupRestoreUpload.
type PostSystemBackupRestoreUploadOperationResponse struct {
	HttpResponse *http.Response
}

// PostSystemBackupRestoreUpload calls POST /api/v3/system/backup/restore/upload.
func (c Client) PostSystemBackupRestoreUpload(ctx context.Context) (result PostSystemBackupRestoreUploadOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodPost,
		Path:       "/api/v3/system/backup/restore/upload",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
