// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// BackupType is the "BackupType" enum.
type BackupType string

// Values of BackupType.
const (
	BackupTypeScheduled BackupType = "scheduled"
	BackupTypeManual    BackupType = "manual"
	BackupTypeUpdate    BackupType = "update"
)

// PossibleValuesForBackupType returns every value of BackupType.
func PossibleValuesForBackupType() []string {
	return []string{
		string(BackupTypeScheduled),
		string(BackupTypeManual),
		string(BackupTypeUpdate),
	}
}
