// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetSystemBackupOperationResponse is the result of GetSystemBackup.
type GetSystemBackupOperationResponse struct {
	HttpResponse *http.Response
	Model        []BackupResource
}

// GetSystemBackup calls GET /api/v3/system/backup.
func (c Client) GetSystemBackup(ctx context.Context) (result GetSystemBackupOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/system/backup",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
