// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// BlocklistResourcePagingResource is the "BlocklistResourcePagingResource" schema.
type BlocklistResourcePagingResource struct {
	Page          int                 `json:"page,omitempty"`
	PageSize      int                 `json:"pageSize,omitempty"`
	Records       []BlocklistResource `json:"records,omitzero"`
	SortDirection SortDirection       `json:"sortDirection,omitempty"`
	SortKey       string              `json:"sortKey,omitempty"`
	TotalRecords  int                 `json:"totalRecords,omitempty"`
}
