// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// BlocklistBulkResource is the "BlocklistBulkResource" schema.
type BlocklistBulkResource struct {
	Ids []int `json:"ids,omitzero"`
}
