// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// DeleteBlocklistByIdOperationResponse is the result of DeleteBlocklistById.
type DeleteBlocklistByIdOperationResponse struct {
	HttpResponse *http.Response
}

// DeleteBlocklistById calls DELETE /api/v3/blocklist/{id}.
func (c Client) DeleteBlocklistById(ctx context.Context, id int) (result DeleteBlocklistByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodDelete,
		Path:       fmt.Sprintf("/api/v3/blocklist/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
