// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetBlocklistOperationResponse is the result of GetBlocklist.
type GetBlocklistOperationResponse struct {
	HttpResponse *http.Response
	Model        *BlocklistResourcePagingResource
}

// GetBlocklistOperationOptions holds the query and header parameters of GetBlocklist.
type GetBlocklistOperationOptions struct {
	Page          int
	PageSize      int
	SortKey       string
	SortDirection SortDirection
	SeriesIds     []int
	Protocols     []DownloadProtocol
}

// ToHeaders returns the header parameters the options set.
func (o GetBlocklistOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetBlocklistOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Page != 0 {
		out.Append("page", strconv.Itoa(o.Page))
	}
	if o.PageSize != 0 {
		out.Append("pageSize", strconv.Itoa(o.PageSize))
	}
	if o.SortKey != "" {
		out.Append("sortKey", o.SortKey)
	}
	if o.SortDirection != "" {
		out.Append("sortDirection", string(o.SortDirection))
	}
	for _, v := range o.SeriesIds {
		out.Append("seriesIds", strconv.Itoa(v))
	}
	for _, v := range o.Protocols {
		out.Append("protocols", string(v))
	}
	return &out
}

// GetBlocklist calls GET /api/v3/blocklist.
func (c Client) GetBlocklist(ctx context.Context, options GetBlocklistOperationOptions) (result GetBlocklistOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/blocklist",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model BlocklistResourcePagingResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}

// GetBlocklistCompleteResult is every result GetBlocklistComplete loaded.
type GetBlocklistCompleteResult struct {
	LatestHttpResponse *http.Response
	Items              []BlocklistResource
}

// GetBlocklistComplete calls GetBlocklist page by page, from options.Page (the first page
// when unset), until every result is loaded. options.PageSize is the page size,
// client.DefaultPageSize when unset.
func (c Client) GetBlocklistComplete(ctx context.Context, options GetBlocklistOperationOptions) (result GetBlocklistCompleteResult, err error) {
	if options.PageSize <= 0 {
		options.PageSize = client.DefaultPageSize
	}
	if options.Page <= 0 {
		options.Page = 1
	}
	for {
		var page GetBlocklistOperationResponse
		page, err = c.GetBlocklist(ctx, options)
		result.LatestHttpResponse = page.HttpResponse
		if err != nil {
			err = fmt.Errorf("loading results: %w", err)
			return
		}
		if page.Model == nil || len(page.Model.Records) == 0 {
			return
		}
		result.Items = append(result.Items, page.Model.Records...)
		// a short page is the last; so is the page that reaches the total
		if len(page.Model.Records) < options.PageSize || page.Model.TotalRecords > 0 && options.Page*options.PageSize >= page.Model.TotalRecords {
			return
		}
		options.Page++
	}
}
