// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// BlocklistResource is the "BlocklistResource" schema.
type BlocklistResource struct {
	CustomFormats []CustomFormatResource `json:"customFormats,omitzero"`
	Date          string                 `json:"date,omitempty"`
	EpisodeIds    []int                  `json:"episodeIds,omitzero"`
	Id            int                    `json:"id,omitempty"`
	Indexer       string                 `json:"indexer,omitempty"`
	Languages     []Language             `json:"languages,omitzero"`
	Message       string                 `json:"message,omitempty"`
	Protocol      DownloadProtocol       `json:"protocol,omitempty"`
	Quality       *QualityModel          `json:"quality,omitempty"`
	Series        *SeriesResource        `json:"series,omitempty"`
	SeriesId      int                    `json:"seriesId,omitempty"`
	SourceTitle   string                 `json:"sourceTitle,omitempty"`
}
