// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"io"
	"net/http"
	"testing"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

func TestOperationGetFeedV3CalendarSonarrIcs(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 200, "text/calendar", "file bytes")
	result, err := c.GetFeedV3CalendarSonarrIcs(t.Context(), GetFeedV3CalendarSonarrIcsOperationOptions{
		PastDays:      7,
		FutureDays:    7,
		Tags:          "v-Tags",
		Unmonitored:   new(true),
		PremieresOnly: new(true),
		AsAllDay:      new(true),
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodGet, "/feed/v3/calendar/sonarr.ics")
	expectQuery(t, r, "pastDays", "7")
	expectQuery(t, r, "futureDays", "7")
	expectQuery(t, r, "tags", "v-Tags")
	expectQuery(t, r, "unmonitored", "true")
	expectQuery(t, r, "premieresOnly", "true")
	expectQuery(t, r, "asAllDay", "true")
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 200 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}
	streamed, _ := io.ReadAll(result.HttpResponse.Body)
	_ = result.HttpResponse.Body.Close()
	if string(streamed) != "file bytes" {
		t.Errorf("streamed body = %q", streamed)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.GetFeedV3CalendarSonarrIcs(t.Context(), GetFeedV3CalendarSonarrIcsOperationOptions{
		PastDays:      7,
		FutureDays:    7,
		Tags:          "v-Tags",
		Unmonitored:   new(true),
		PremieresOnly: new(true),
		AsAllDay:      new(true),
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
