// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"net/http"
	"testing"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

func TestOperationGetCalendar(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 200, "application/json", "[{}]")
	result, err := c.GetCalendar(t.Context(), GetCalendarOperationOptions{
		Start:                "v-Start",
		End:                  "v-End",
		Unmonitored:          new(true),
		IncludeSeries:        new(true),
		IncludeEpisodeFile:   new(true),
		IncludeEpisodeImages: new(true),
		Tags:                 "v-Tags",
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodGet, "/api/v3/calendar")
	expectQuery(t, r, "start", "v-Start")
	expectQuery(t, r, "end", "v-End")
	expectQuery(t, r, "unmonitored", "true")
	expectQuery(t, r, "includeSeries", "true")
	expectQuery(t, r, "includeEpisodeFile", "true")
	expectQuery(t, r, "includeEpisodeImages", "true")
	expectQuery(t, r, "tags", "v-Tags")
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 200 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}
	if result.Model == nil {
		t.Error("the model was not decoded")
	}

	// an answer that does not decode is an error, with the response
	c, _ = newOperationServer(t, 200, "application/json", "<html>")
	result, err = c.GetCalendar(t.Context(), GetCalendarOperationOptions{
		Start:                "v-Start",
		End:                  "v-End",
		Unmonitored:          new(true),
		IncludeSeries:        new(true),
		IncludeEpisodeFile:   new(true),
		IncludeEpisodeImages: new(true),
		Tags:                 "v-Tags",
	})
	if err == nil || client.StatusCode(err) != 0 || result.HttpResponse == nil {
		t.Errorf("an answer that does not decode = %v", err)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.GetCalendar(t.Context(), GetCalendarOperationOptions{
		Start:                "v-Start",
		End:                  "v-End",
		Unmonitored:          new(true),
		IncludeSeries:        new(true),
		IncludeEpisodeFile:   new(true),
		IncludeEpisodeImages: new(true),
		Tags:                 "v-Tags",
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
