// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetCalendarOperationResponse is the result of GetCalendar.
type GetCalendarOperationResponse struct {
	HttpResponse *http.Response
	Model        []EpisodeResource
}

// GetCalendarOperationOptions holds the query and header parameters of GetCalendar.
type GetCalendarOperationOptions struct {
	Start                string
	End                  string
	Unmonitored          *bool
	IncludeSeries        *bool
	IncludeEpisodeFile   *bool
	IncludeEpisodeImages *bool
	Tags                 string
}

// ToHeaders returns the header parameters the options set.
func (o GetCalendarOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetCalendarOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Start != "" {
		out.Append("start", o.Start)
	}
	if o.End != "" {
		out.Append("end", o.End)
	}
	if o.Unmonitored != nil {
		out.Append("unmonitored", strconv.FormatBool(*o.Unmonitored))
	}
	if o.IncludeSeries != nil {
		out.Append("includeSeries", strconv.FormatBool(*o.IncludeSeries))
	}
	if o.IncludeEpisodeFile != nil {
		out.Append("includeEpisodeFile", strconv.FormatBool(*o.IncludeEpisodeFile))
	}
	if o.IncludeEpisodeImages != nil {
		out.Append("includeEpisodeImages", strconv.FormatBool(*o.IncludeEpisodeImages))
	}
	if o.Tags != "" {
		out.Append("tags", o.Tags)
	}
	return &out
}

// GetCalendar calls GET /api/v3/calendar.
func (c Client) GetCalendar(ctx context.Context, options GetCalendarOperationOptions) (result GetCalendarOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/calendar",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
