// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetFeedV3CalendarSonarrIcsOperationResponse is the result of GetFeedV3CalendarSonarrIcs.
//
// The operation answers text/calendar, left unread in HttpResponse.Body, which
// the caller must close.
type GetFeedV3CalendarSonarrIcsOperationResponse struct {
	HttpResponse *http.Response
}

// GetFeedV3CalendarSonarrIcsOperationOptions holds the query and header parameters of GetFeedV3CalendarSonarrIcs.
type GetFeedV3CalendarSonarrIcsOperationOptions struct {
	PastDays      int
	FutureDays    int
	Tags          string
	Unmonitored   *bool
	PremieresOnly *bool
	AsAllDay      *bool
}

// ToHeaders returns the header parameters the options set.
func (o GetFeedV3CalendarSonarrIcsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetFeedV3CalendarSonarrIcsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.PastDays != 0 {
		out.Append("pastDays", strconv.Itoa(o.PastDays))
	}
	if o.FutureDays != 0 {
		out.Append("futureDays", strconv.Itoa(o.FutureDays))
	}
	if o.Tags != "" {
		out.Append("tags", o.Tags)
	}
	if o.Unmonitored != nil {
		out.Append("unmonitored", strconv.FormatBool(*o.Unmonitored))
	}
	if o.PremieresOnly != nil {
		out.Append("premieresOnly", strconv.FormatBool(*o.PremieresOnly))
	}
	if o.AsAllDay != nil {
		out.Append("asAllDay", strconv.FormatBool(*o.AsAllDay))
	}
	return &out
}

// GetFeedV3CalendarSonarrIcs calls GET /feed/v3/calendar/sonarr.ics.
func (c Client) GetFeedV3CalendarSonarrIcs(ctx context.Context, options GetFeedV3CalendarSonarrIcsOperationOptions) (result GetFeedV3CalendarSonarrIcsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:     http.MethodGet,
		OptionsObject:  options,
		Path:           "/feed/v3/calendar/sonarr.ics",
		StreamResponse: true,
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
