// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"slices"
	"testing"
)

// operationServer is a canned server that answers every request with one
// status, content type and body, and records what it was sent.
type operationServer struct {
	*httptest.Server
	requests []*http.Request
	bodies   []string
}

// newOperationServer starts a canned server for the test and a client for it.
func newOperationServer(t *testing.T, status int, contentType, body string) (*Client, *operationServer) {
	t.Helper()

	s := &operationServer{}
	s.Server = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		b, _ := io.ReadAll(r.Body)
		s.requests = append(s.requests, r.Clone(r.Context()))
		s.bodies = append(s.bodies, string(b))
		if contentType != "" {
			w.Header().Set("Content-Type", contentType)
		}
		w.WriteHeader(status)
		_, _ = io.WriteString(w, body)
	}))
	t.Cleanup(s.Close)
	c, err := New(s.URL, "test-key")
	if err != nil {
		t.Fatal(err)
	}
	// the server's own client: closing a test server closes the idle
	// connections of http.DefaultTransport, which would break the
	// parallel tests sharing it
	c.Client.HTTPClient = s.Client()

	return c, s
}

// only returns the one request the server received.
func (s *operationServer) only(t *testing.T) (*http.Request, string) {
	t.Helper()

	if len(s.requests) != 1 {
		t.Fatalf("the server received %d requests, want 1", len(s.requests))
	}

	return s.requests[0], s.bodies[0]
}

// expectRequest checks the method and escaped path of a request.
func expectRequest(t *testing.T, r *http.Request, method, path string) {
	t.Helper()

	if r.Method != method || r.URL.EscapedPath() != path {
		t.Errorf("request = %s %s, want %s %s", r.Method, r.URL.EscapedPath(), method, path)
	}
}

// expectQuery checks the values sent for one query parameter.
func expectQuery(t *testing.T, r *http.Request, name string, want ...string) {
	t.Helper()

	if got := r.URL.Query()[name]; !slices.Equal(got, want) {
		t.Errorf("query %s = %q, want %q", name, got, want)
	}
}

// pagedServer answers every page with one record of total records and
// records the page number each request asked for.
func pagedServer(t *testing.T, pageParam, item string, total int) (*Client, *[]string) {
	t.Helper()

	var pages []string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		pages = append(pages, r.URL.Query().Get(pageParam))
		w.Header().Set("Content-Type", "application/json")
		_, _ = fmt.Fprintf(w, "{\"records\":[%s],\"totalRecords\":%d}", item, total)
	}))
	t.Cleanup(srv.Close)
	c, err := New(srv.URL, "test-key")
	if err != nil {
		t.Fatal(err)
	}
	c.Client.HTTPClient = srv.Client()

	return c, &pages
}

func TestNew(t *testing.T) {
	t.Parallel()

	if _, err := New("http://server:8989", ""); err == nil {
		t.Error("New without an API key succeeded")
	}
	if _, err := New("server", "test-key"); err == nil {
		t.Error("New without a scheme succeeded")
	}
	c, err := New("http://server:8989/", "test-key")
	if err != nil || c.Client.BaseURL != "http://server:8989" {
		t.Errorf("New = %+v, %v", c, err)
	}
}
