// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"errors"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// Client is a client for the Sonarr API; each of its operations is a method.
// Requests go through Client.Client, the shared base client.
type Client struct {
	Client *client.Client
}

// New returns a client for the Sonarr server at baseURL (scheme and host,
// optionally the URL base it is configured with) that authenticates with its
// API key.
func New(baseURL, apiKey string) (*Client, error) {
	if apiKey == "" {
		return nil, errors.New("API key is required")
	}
	c, err := client.New(baseURL, client.APIKey(apiKey))
	if err != nil {
		return nil, err
	}

	return &Client{Client: c}, nil
}
