// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// MediaCover is the "MediaCover" schema.
type MediaCover struct {
	CoverType MediaCoverTypes `json:"coverType,omitempty"`
	RemoteUrl string          `json:"remoteUrl,omitempty"`
	Url       string          `json:"url,omitempty"`
}
