// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// ProviderTestAllResult is the "ProviderTestAllResult" schema.
//
// The outcome of testing one provider.
type ProviderTestAllResult struct {
	Id                 int                 `json:"id,omitempty"`
	IsValid            *bool               `json:"isValid,omitempty"`
	ValidationFailures []ValidationFailure `json:"validationFailures,omitzero"`
}
