// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// SeasonStatisticsResource is the "SeasonStatisticsResource" schema.
type SeasonStatisticsResource struct {
	EpisodeCount      int      `json:"episodeCount,omitempty"`
	EpisodeFileCount  int      `json:"episodeFileCount,omitempty"`
	NextAiring        string   `json:"nextAiring,omitempty"`
	PercentOfEpisodes float64  `json:"percentOfEpisodes,omitempty"`
	PreviousAiring    string   `json:"previousAiring,omitempty"`
	ReleaseGroups     []string `json:"releaseGroups,omitzero"`
	SizeOnDisk        int64    `json:"sizeOnDisk,omitempty"`
	TotalEpisodeCount int      `json:"totalEpisodeCount,omitempty"`
}
