// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// LanguageProfileResource is the "LanguageProfileResource" schema.
type LanguageProfileResource struct {
	Cutoff         *Language                     `json:"cutoff,omitempty"`
	Id             int                           `json:"id,omitempty"`
	Languages      []LanguageProfileItemResource `json:"languages,omitzero"`
	Name           string                        `json:"name,omitempty"`
	UpgradeAllowed *bool                         `json:"upgradeAllowed,omitempty"`
}
