// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// CommandPriority is the "CommandPriority" enum.
type CommandPriority string

// Values of CommandPriority.
const (
	CommandPriorityNormal CommandPriority = "normal"
	CommandPriorityHigh   CommandPriority = "high"
	CommandPriorityLow    CommandPriority = "low"
)

// PossibleValuesForCommandPriority returns every value of CommandPriority.
func PossibleValuesForCommandPriority() []string {
	return []string{
		string(CommandPriorityNormal),
		string(CommandPriorityHigh),
		string(CommandPriorityLow),
	}
}

// CommandResult is the "CommandResult" enum.
type CommandResult string

// Values of CommandResult.
const (
	CommandResultUnknown      CommandResult = "unknown"
	CommandResultSuccessful   CommandResult = "successful"
	CommandResultUnsuccessful CommandResult = "unsuccessful"
)

// PossibleValuesForCommandResult returns every value of CommandResult.
func PossibleValuesForCommandResult() []string {
	return []string{
		string(CommandResultUnknown),
		string(CommandResultSuccessful),
		string(CommandResultUnsuccessful),
	}
}

// CommandStatus is the "CommandStatus" enum.
type CommandStatus string

// Values of CommandStatus.
const (
	CommandStatusQueued    CommandStatus = "queued"
	CommandStatusStarted   CommandStatus = "started"
	CommandStatusCompleted CommandStatus = "completed"
	CommandStatusFailed    CommandStatus = "failed"
	CommandStatusAborted   CommandStatus = "aborted"
	CommandStatusCancelled CommandStatus = "cancelled"
	CommandStatusOrphaned  CommandStatus = "orphaned"
)

// PossibleValuesForCommandStatus returns every value of CommandStatus.
func PossibleValuesForCommandStatus() []string {
	return []string{
		string(CommandStatusQueued),
		string(CommandStatusStarted),
		string(CommandStatusCompleted),
		string(CommandStatusFailed),
		string(CommandStatusAborted),
		string(CommandStatusCancelled),
		string(CommandStatusOrphaned),
	}
}

// CommandTrigger is the "CommandTrigger" enum.
type CommandTrigger string

// Values of CommandTrigger.
const (
	CommandTriggerUnspecified CommandTrigger = "unspecified"
	CommandTriggerManual      CommandTrigger = "manual"
	CommandTriggerScheduled   CommandTrigger = "scheduled"
)

// PossibleValuesForCommandTrigger returns every value of CommandTrigger.
func PossibleValuesForCommandTrigger() []string {
	return []string{
		string(CommandTriggerUnspecified),
		string(CommandTriggerManual),
		string(CommandTriggerScheduled),
	}
}
