// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// EpisodeFileResource is the "EpisodeFileResource" schema.
type EpisodeFileResource struct {
	CustomFormatScore   int                    `json:"customFormatScore,omitempty"`
	CustomFormats       []CustomFormatResource `json:"customFormats,omitzero"`
	DateAdded           string                 `json:"dateAdded,omitempty"`
	Id                  int                    `json:"id,omitempty"`
	IndexerFlags        int                    `json:"indexerFlags,omitempty"`
	Languages           []Language             `json:"languages,omitzero"`
	MediaInfo           *MediaInfoResource     `json:"mediaInfo,omitempty"`
	Path                string                 `json:"path,omitempty"`
	Quality             *QualityModel          `json:"quality,omitempty"`
	QualityCutoffNotMet *bool                  `json:"qualityCutoffNotMet,omitempty"`
	RelativePath        string                 `json:"relativePath,omitempty"`
	ReleaseGroup        string                 `json:"releaseGroup,omitempty"`
	ReleaseType         ReleaseType            `json:"releaseType,omitempty"`
	SceneName           string                 `json:"sceneName,omitempty"`
	SeasonNumber        int                    `json:"seasonNumber,omitempty"`
	SeriesId            int                    `json:"seriesId,omitempty"`
	Size                int64                  `json:"size,omitempty"`
}
