// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// QualityModel is the "QualityModel" schema.
type QualityModel struct {
	Quality  *Quality  `json:"quality,omitempty"`
	Revision *Revision `json:"revision,omitempty"`
}
