// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// MediaInfoResource is the "MediaInfoResource" schema.
type MediaInfoResource struct {
	AudioBitrate          int64   `json:"audioBitrate,omitempty"`
	AudioChannels         float64 `json:"audioChannels,omitempty"`
	AudioCodec            string  `json:"audioCodec,omitempty"`
	AudioLanguages        string  `json:"audioLanguages,omitempty"`
	AudioStreamCount      int     `json:"audioStreamCount,omitempty"`
	Id                    int     `json:"id,omitempty"`
	Resolution            string  `json:"resolution,omitempty"`
	RunTime               string  `json:"runTime,omitempty"`
	ScanType              string  `json:"scanType,omitempty"`
	Subtitles             string  `json:"subtitles,omitempty"`
	VideoBitDepth         int     `json:"videoBitDepth,omitempty"`
	VideoBitrate          int64   `json:"videoBitrate,omitempty"`
	VideoCodec            string  `json:"videoCodec,omitempty"`
	VideoDynamicRange     string  `json:"videoDynamicRange,omitempty"`
	VideoDynamicRangeType string  `json:"videoDynamicRangeType,omitempty"`
	VideoFps              float64 `json:"videoFps,omitempty"`
}
