// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// ReleaseResource is the "ReleaseResource" schema.
type ReleaseResource struct {
	AbsoluteEpisodeNumbers       []int                    `json:"absoluteEpisodeNumbers,omitzero"`
	Age                          int                      `json:"age,omitempty"`
	AgeHours                     float64                  `json:"ageHours,omitempty"`
	AgeMinutes                   float64                  `json:"ageMinutes,omitempty"`
	AirDate                      string                   `json:"airDate,omitempty"`
	Approved                     *bool                    `json:"approved,omitempty"`
	CommentUrl                   string                   `json:"commentUrl,omitempty"`
	CustomFormatScore            int                      `json:"customFormatScore,omitempty"`
	CustomFormats                []CustomFormatResource   `json:"customFormats,omitzero"`
	DownloadAllowed              *bool                    `json:"downloadAllowed,omitempty"`
	DownloadClient               string                   `json:"downloadClient,omitempty"`
	DownloadClientId             int                      `json:"downloadClientId,omitempty"`
	DownloadUrl                  string                   `json:"downloadUrl,omitempty"`
	EpisodeId                    int                      `json:"episodeId,omitempty"`
	EpisodeIds                   []int                    `json:"episodeIds,omitzero"`
	EpisodeNumbers               []int                    `json:"episodeNumbers,omitzero"`
	EpisodeRequested             *bool                    `json:"episodeRequested,omitempty"`
	FullSeason                   *bool                    `json:"fullSeason,omitempty"`
	Guid                         string                   `json:"guid,omitempty"`
	Id                           int                      `json:"id,omitempty"`
	ImdbId                       string                   `json:"imdbId,omitempty"`
	Indexer                      string                   `json:"indexer,omitempty"`
	IndexerFlags                 int                      `json:"indexerFlags,omitempty"`
	IndexerId                    int                      `json:"indexerId,omitempty"`
	InfoHash                     string                   `json:"infoHash,omitempty"`
	InfoUrl                      string                   `json:"infoUrl,omitempty"`
	IsAbsoluteNumbering          *bool                    `json:"isAbsoluteNumbering,omitempty"`
	IsDaily                      *bool                    `json:"isDaily,omitempty"`
	IsPossibleSpecialEpisode     *bool                    `json:"isPossibleSpecialEpisode,omitempty"`
	LanguageWeight               int                      `json:"languageWeight,omitempty"`
	Languages                    []Language               `json:"languages,omitzero"`
	Leechers                     int                      `json:"leechers,omitempty"`
	MagnetUrl                    string                   `json:"magnetUrl,omitempty"`
	MappedAbsoluteEpisodeNumbers []int                    `json:"mappedAbsoluteEpisodeNumbers,omitzero"`
	MappedEpisodeInfo            []ReleaseEpisodeResource `json:"mappedEpisodeInfo,omitzero"`
	MappedEpisodeNumbers         []int                    `json:"mappedEpisodeNumbers,omitzero"`
	MappedSeasonNumber           int                      `json:"mappedSeasonNumber,omitempty"`
	MappedSeriesId               int                      `json:"mappedSeriesId,omitempty"`
	Protocol                     DownloadProtocol         `json:"protocol,omitempty"`
	PublishDate                  string                   `json:"publishDate,omitempty"`
	Quality                      *QualityModel            `json:"quality,omitempty"`
	QualityWeight                int                      `json:"qualityWeight,omitempty"`
	Rejected                     *bool                    `json:"rejected,omitempty"`
	Rejections                   []string                 `json:"rejections,omitzero"`
	ReleaseGroup                 string                   `json:"releaseGroup,omitempty"`
	ReleaseHash                  string                   `json:"releaseHash,omitempty"`
	ReleaseWeight                int                      `json:"releaseWeight,omitempty"`
	SceneMapping                 *AlternateTitleResource  `json:"sceneMapping,omitempty"`
	SceneSource                  *bool                    `json:"sceneSource,omitempty"`
	SeasonNumber                 int                      `json:"seasonNumber,omitempty"`
	Seeders                      int                      `json:"seeders,omitempty"`
	SeriesId                     int                      `json:"seriesId,omitempty"`
	SeriesTitle                  string                   `json:"seriesTitle,omitempty"`
	ShouldOverride               *bool                    `json:"shouldOverride,omitempty"`
	Size                         int64                    `json:"size,omitempty"`
	Special                      *bool                    `json:"special,omitempty"`
	SubGroup                     string                   `json:"subGroup,omitempty"`
	TemporarilyRejected          *bool                    `json:"temporarilyRejected,omitempty"`
	Title                        string                   `json:"title,omitempty"`
	TvRageId                     int                      `json:"tvRageId,omitempty"`
	TvdbId                       int                      `json:"tvdbId,omitempty"`
}
