// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// SeriesResource is the "SeriesResource" schema.
type SeriesResource struct {
	AddOptions        *AddSeriesOptions         `json:"addOptions,omitempty"`
	Added             string                    `json:"added,omitempty"`
	AirTime           string                    `json:"airTime,omitempty"`
	AlternateTitles   []AlternateTitleResource  `json:"alternateTitles,omitzero"`
	Certification     string                    `json:"certification,omitempty"`
	CleanTitle        string                    `json:"cleanTitle,omitempty"`
	Ended             *bool                     `json:"ended,omitempty"`
	EpisodesChanged   *bool                     `json:"episodesChanged,omitempty"`
	FirstAired        string                    `json:"firstAired,omitempty"`
	Folder            string                    `json:"folder,omitempty"`
	Genres            []string                  `json:"genres,omitzero"`
	Id                int                       `json:"id,omitempty"`
	Images            []MediaCover              `json:"images,omitzero"`
	ImdbId            string                    `json:"imdbId,omitempty"`
	LanguageProfileId int                       `json:"languageProfileId,omitempty"`
	LastAired         string                    `json:"lastAired,omitempty"`
	MonitorNewItems   NewItemMonitorTypes       `json:"monitorNewItems,omitempty"`
	Monitored         *bool                     `json:"monitored,omitempty"`
	Network           string                    `json:"network,omitempty"`
	NextAiring        string                    `json:"nextAiring,omitempty"`
	OriginalLanguage  *Language                 `json:"originalLanguage,omitempty"`
	Overview          string                    `json:"overview,omitempty"`
	Path              string                    `json:"path,omitempty"`
	PreviousAiring    string                    `json:"previousAiring,omitempty"`
	ProfileName       string                    `json:"profileName,omitempty"`
	QualityProfileId  int                       `json:"qualityProfileId,omitempty"`
	Ratings           *Ratings                  `json:"ratings,omitempty"`
	RemotePoster      string                    `json:"remotePoster,omitempty"`
	RootFolderPath    string                    `json:"rootFolderPath,omitempty"`
	Runtime           int                       `json:"runtime,omitempty"`
	SeasonFolder      *bool                     `json:"seasonFolder,omitempty"`
	Seasons           []SeasonResource          `json:"seasons,omitzero"`
	SeriesType        SeriesTypes               `json:"seriesType,omitempty"`
	SortTitle         string                    `json:"sortTitle,omitempty"`
	Statistics        *SeriesStatisticsResource `json:"statistics,omitempty"`
	Status            SeriesStatusType          `json:"status,omitempty"`
	Tags              []int                     `json:"tags,omitzero"`
	Title             string                    `json:"title,omitempty"`
	TitleSlug         string                    `json:"titleSlug,omitempty"`
	TmdbId            int                       `json:"tmdbId,omitempty"`
	TvMazeId          int                       `json:"tvMazeId,omitempty"`
	TvRageId          int                       `json:"tvRageId,omitempty"`
	TvdbId            int                       `json:"tvdbId,omitempty"`
	UseSceneNumbering *bool                     `json:"useSceneNumbering,omitempty"`
	Year              int                       `json:"year,omitempty"`
}
