// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// SeriesStatisticsResource is the "SeriesStatisticsResource" schema.
type SeriesStatisticsResource struct {
	EpisodeCount      int      `json:"episodeCount,omitempty"`
	EpisodeFileCount  int      `json:"episodeFileCount,omitempty"`
	PercentOfEpisodes float64  `json:"percentOfEpisodes,omitempty"`
	ReleaseGroups     []string `json:"releaseGroups,omitzero"`
	SeasonCount       int      `json:"seasonCount,omitempty"`
	SizeOnDisk        int64    `json:"sizeOnDisk,omitempty"`
	TotalEpisodeCount int      `json:"totalEpisodeCount,omitempty"`
}
