// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// Revision is the "Revision" schema.
type Revision struct {
	IsRepack *bool `json:"isRepack,omitempty"`
	Real     int   `json:"real,omitempty"`
	Version  int   `json:"version,omitempty"`
}
