// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// ApplyTags is the "ApplyTags" enum.
type ApplyTags string

// Values of ApplyTags.
const (
	ApplyTagsAdd     ApplyTags = "add"
	ApplyTagsRemove  ApplyTags = "remove"
	ApplyTagsReplace ApplyTags = "replace"
)

// PossibleValuesForApplyTags returns every value of ApplyTags.
func PossibleValuesForApplyTags() []string {
	return []string{
		string(ApplyTagsAdd),
		string(ApplyTagsRemove),
		string(ApplyTagsReplace),
	}
}

// AuthenticationType is the "AuthenticationType" enum.
type AuthenticationType string

// Values of AuthenticationType.
const (
	AuthenticationTypeNone     AuthenticationType = "none"
	AuthenticationTypeBasic    AuthenticationType = "basic"
	AuthenticationTypeForms    AuthenticationType = "forms"
	AuthenticationTypeExternal AuthenticationType = "external"
)

// PossibleValuesForAuthenticationType returns every value of AuthenticationType.
func PossibleValuesForAuthenticationType() []string {
	return []string{
		string(AuthenticationTypeNone),
		string(AuthenticationTypeBasic),
		string(AuthenticationTypeForms),
		string(AuthenticationTypeExternal),
	}
}

// DownloadProtocol is the "DownloadProtocol" enum.
type DownloadProtocol string

// Values of DownloadProtocol.
const (
	DownloadProtocolUnknown DownloadProtocol = "unknown"
	DownloadProtocolUsenet  DownloadProtocol = "usenet"
	DownloadProtocolTorrent DownloadProtocol = "torrent"
)

// PossibleValuesForDownloadProtocol returns every value of DownloadProtocol.
func PossibleValuesForDownloadProtocol() []string {
	return []string{
		string(DownloadProtocolUnknown),
		string(DownloadProtocolUsenet),
		string(DownloadProtocolTorrent),
	}
}

// MediaCoverTypes is the "MediaCoverTypes" enum.
type MediaCoverTypes string

// Values of MediaCoverTypes.
const (
	MediaCoverTypesUnknown    MediaCoverTypes = "unknown"
	MediaCoverTypesPoster     MediaCoverTypes = "poster"
	MediaCoverTypesBanner     MediaCoverTypes = "banner"
	MediaCoverTypesFanart     MediaCoverTypes = "fanart"
	MediaCoverTypesScreenshot MediaCoverTypes = "screenshot"
	MediaCoverTypesHeadshot   MediaCoverTypes = "headshot"
	MediaCoverTypesClearlogo  MediaCoverTypes = "clearlogo"
)

// PossibleValuesForMediaCoverTypes returns every value of MediaCoverTypes.
func PossibleValuesForMediaCoverTypes() []string {
	return []string{
		string(MediaCoverTypesUnknown),
		string(MediaCoverTypesPoster),
		string(MediaCoverTypesBanner),
		string(MediaCoverTypesFanart),
		string(MediaCoverTypesScreenshot),
		string(MediaCoverTypesHeadshot),
		string(MediaCoverTypesClearlogo),
	}
}

// MonitorTypes is the "MonitorTypes" enum.
type MonitorTypes string

// Values of MonitorTypes.
const (
	MonitorTypesUnknown           MonitorTypes = "unknown"
	MonitorTypesAll               MonitorTypes = "all"
	MonitorTypesFuture            MonitorTypes = "future"
	MonitorTypesMissing           MonitorTypes = "missing"
	MonitorTypesExisting          MonitorTypes = "existing"
	MonitorTypesFirstSeason       MonitorTypes = "firstSeason"
	MonitorTypesLastSeason        MonitorTypes = "lastSeason"
	MonitorTypesLatestSeason      MonitorTypes = "latestSeason"
	MonitorTypesPilot             MonitorTypes = "pilot"
	MonitorTypesRecent            MonitorTypes = "recent"
	MonitorTypesMonitorSpecials   MonitorTypes = "monitorSpecials"
	MonitorTypesUnmonitorSpecials MonitorTypes = "unmonitorSpecials"
	MonitorTypesNone              MonitorTypes = "none"
	MonitorTypesSkip              MonitorTypes = "skip"
)

// PossibleValuesForMonitorTypes returns every value of MonitorTypes.
func PossibleValuesForMonitorTypes() []string {
	return []string{
		string(MonitorTypesUnknown),
		string(MonitorTypesAll),
		string(MonitorTypesFuture),
		string(MonitorTypesMissing),
		string(MonitorTypesExisting),
		string(MonitorTypesFirstSeason),
		string(MonitorTypesLastSeason),
		string(MonitorTypesLatestSeason),
		string(MonitorTypesPilot),
		string(MonitorTypesRecent),
		string(MonitorTypesMonitorSpecials),
		string(MonitorTypesUnmonitorSpecials),
		string(MonitorTypesNone),
		string(MonitorTypesSkip),
	}
}

// NewItemMonitorTypes is the "NewItemMonitorTypes" enum.
type NewItemMonitorTypes string

// Values of NewItemMonitorTypes.
const (
	NewItemMonitorTypesAll  NewItemMonitorTypes = "all"
	NewItemMonitorTypesNone NewItemMonitorTypes = "none"
)

// PossibleValuesForNewItemMonitorTypes returns every value of NewItemMonitorTypes.
func PossibleValuesForNewItemMonitorTypes() []string {
	return []string{
		string(NewItemMonitorTypesAll),
		string(NewItemMonitorTypesNone),
	}
}

// PrivacyLevel is the "PrivacyLevel" enum.
type PrivacyLevel string

// Values of PrivacyLevel.
const (
	PrivacyLevelNormal   PrivacyLevel = "normal"
	PrivacyLevelPassword PrivacyLevel = "password"
	PrivacyLevelApiKey   PrivacyLevel = "apiKey"
	PrivacyLevelUserName PrivacyLevel = "userName"
)

// PossibleValuesForPrivacyLevel returns every value of PrivacyLevel.
func PossibleValuesForPrivacyLevel() []string {
	return []string{
		string(PrivacyLevelNormal),
		string(PrivacyLevelPassword),
		string(PrivacyLevelApiKey),
		string(PrivacyLevelUserName),
	}
}

// ProviderMessageType is the "ProviderMessageType" enum.
type ProviderMessageType string

// Values of ProviderMessageType.
const (
	ProviderMessageTypeInfo    ProviderMessageType = "info"
	ProviderMessageTypeWarning ProviderMessageType = "warning"
	ProviderMessageTypeError   ProviderMessageType = "error"
)

// PossibleValuesForProviderMessageType returns every value of ProviderMessageType.
func PossibleValuesForProviderMessageType() []string {
	return []string{
		string(ProviderMessageTypeInfo),
		string(ProviderMessageTypeWarning),
		string(ProviderMessageTypeError),
	}
}

// QualitySource is the "QualitySource" enum.
type QualitySource string

// Values of QualitySource.
const (
	QualitySourceUnknown       QualitySource = "unknown"
	QualitySourceTelevision    QualitySource = "television"
	QualitySourceTelevisionRaw QualitySource = "televisionRaw"
	QualitySourceWeb           QualitySource = "web"
	QualitySourceWebRip        QualitySource = "webRip"
	QualitySourceDvd           QualitySource = "dvd"
	QualitySourceBluray        QualitySource = "bluray"
	QualitySourceBlurayRaw     QualitySource = "blurayRaw"
)

// PossibleValuesForQualitySource returns every value of QualitySource.
func PossibleValuesForQualitySource() []string {
	return []string{
		string(QualitySourceUnknown),
		string(QualitySourceTelevision),
		string(QualitySourceTelevisionRaw),
		string(QualitySourceWeb),
		string(QualitySourceWebRip),
		string(QualitySourceDvd),
		string(QualitySourceBluray),
		string(QualitySourceBlurayRaw),
	}
}

// QueueStatus is the "QueueStatus" enum.
type QueueStatus string

// Values of QueueStatus.
const (
	QueueStatusUnknown                   QueueStatus = "unknown"
	QueueStatusQueued                    QueueStatus = "queued"
	QueueStatusPaused                    QueueStatus = "paused"
	QueueStatusDownloading               QueueStatus = "downloading"
	QueueStatusCompleted                 QueueStatus = "completed"
	QueueStatusFailed                    QueueStatus = "failed"
	QueueStatusWarning                   QueueStatus = "warning"
	QueueStatusDelay                     QueueStatus = "delay"
	QueueStatusDownloadClientUnavailable QueueStatus = "downloadClientUnavailable"
	QueueStatusFallback                  QueueStatus = "fallback"
)

// PossibleValuesForQueueStatus returns every value of QueueStatus.
func PossibleValuesForQueueStatus() []string {
	return []string{
		string(QueueStatusUnknown),
		string(QueueStatusQueued),
		string(QueueStatusPaused),
		string(QueueStatusDownloading),
		string(QueueStatusCompleted),
		string(QueueStatusFailed),
		string(QueueStatusWarning),
		string(QueueStatusDelay),
		string(QueueStatusDownloadClientUnavailable),
		string(QueueStatusFallback),
	}
}

// ReleaseType is the "ReleaseType" enum.
type ReleaseType string

// Values of ReleaseType.
const (
	ReleaseTypeUnknown       ReleaseType = "unknown"
	ReleaseTypeSingleEpisode ReleaseType = "singleEpisode"
	ReleaseTypeMultiEpisode  ReleaseType = "multiEpisode"
	ReleaseTypeSeasonPack    ReleaseType = "seasonPack"
)

// PossibleValuesForReleaseType returns every value of ReleaseType.
func PossibleValuesForReleaseType() []string {
	return []string{
		string(ReleaseTypeUnknown),
		string(ReleaseTypeSingleEpisode),
		string(ReleaseTypeMultiEpisode),
		string(ReleaseTypeSeasonPack),
	}
}

// SeriesStatusType is the "SeriesStatusType" enum.
type SeriesStatusType string

// Values of SeriesStatusType.
const (
	SeriesStatusTypeContinuing SeriesStatusType = "continuing"
	SeriesStatusTypeEnded      SeriesStatusType = "ended"
	SeriesStatusTypeUpcoming   SeriesStatusType = "upcoming"
	SeriesStatusTypeDeleted    SeriesStatusType = "deleted"
)

// PossibleValuesForSeriesStatusType returns every value of SeriesStatusType.
func PossibleValuesForSeriesStatusType() []string {
	return []string{
		string(SeriesStatusTypeContinuing),
		string(SeriesStatusTypeEnded),
		string(SeriesStatusTypeUpcoming),
		string(SeriesStatusTypeDeleted),
	}
}

// SeriesTypes is the "SeriesTypes" enum.
type SeriesTypes string

// Values of SeriesTypes.
const (
	SeriesTypesStandard SeriesTypes = "standard"
	SeriesTypesDaily    SeriesTypes = "daily"
	SeriesTypesAnime    SeriesTypes = "anime"
)

// PossibleValuesForSeriesTypes returns every value of SeriesTypes.
func PossibleValuesForSeriesTypes() []string {
	return []string{
		string(SeriesTypesStandard),
		string(SeriesTypesDaily),
		string(SeriesTypesAnime),
	}
}

// SortDirection is the "SortDirection" enum.
type SortDirection string

// Values of SortDirection.
const (
	SortDirectionDefault    SortDirection = "default"
	SortDirectionAscending  SortDirection = "ascending"
	SortDirectionDescending SortDirection = "descending"
)

// PossibleValuesForSortDirection returns every value of SortDirection.
func PossibleValuesForSortDirection() []string {
	return []string{
		string(SortDirectionDefault),
		string(SortDirectionAscending),
		string(SortDirectionDescending),
	}
}

// TrackedDownloadState is the "TrackedDownloadState" enum.
type TrackedDownloadState string

// Values of TrackedDownloadState.
const (
	TrackedDownloadStateDownloading   TrackedDownloadState = "downloading"
	TrackedDownloadStateImportBlocked TrackedDownloadState = "importBlocked"
	TrackedDownloadStateImportPending TrackedDownloadState = "importPending"
	TrackedDownloadStateImporting     TrackedDownloadState = "importing"
	TrackedDownloadStateImported      TrackedDownloadState = "imported"
	TrackedDownloadStateFailedPending TrackedDownloadState = "failedPending"
	TrackedDownloadStateFailed        TrackedDownloadState = "failed"
	TrackedDownloadStateIgnored       TrackedDownloadState = "ignored"
)

// PossibleValuesForTrackedDownloadState returns every value of TrackedDownloadState.
func PossibleValuesForTrackedDownloadState() []string {
	return []string{
		string(TrackedDownloadStateDownloading),
		string(TrackedDownloadStateImportBlocked),
		string(TrackedDownloadStateImportPending),
		string(TrackedDownloadStateImporting),
		string(TrackedDownloadStateImported),
		string(TrackedDownloadStateFailedPending),
		string(TrackedDownloadStateFailed),
		string(TrackedDownloadStateIgnored),
	}
}

// TrackedDownloadStatus is the "TrackedDownloadStatus" enum.
type TrackedDownloadStatus string

// Values of TrackedDownloadStatus.
const (
	TrackedDownloadStatusOk      TrackedDownloadStatus = "ok"
	TrackedDownloadStatusWarning TrackedDownloadStatus = "warning"
	TrackedDownloadStatusError   TrackedDownloadStatus = "error"
)

// PossibleValuesForTrackedDownloadStatus returns every value of TrackedDownloadStatus.
func PossibleValuesForTrackedDownloadStatus() []string {
	return []string{
		string(TrackedDownloadStatusOk),
		string(TrackedDownloadStatusWarning),
		string(TrackedDownloadStatusError),
	}
}

// UpdateMechanism is the "UpdateMechanism" enum.
type UpdateMechanism string

// Values of UpdateMechanism.
const (
	UpdateMechanismBuiltIn  UpdateMechanism = "builtIn"
	UpdateMechanismScript   UpdateMechanism = "script"
	UpdateMechanismExternal UpdateMechanism = "external"
	UpdateMechanismApt      UpdateMechanism = "apt"
	UpdateMechanismDocker   UpdateMechanism = "docker"
)

// PossibleValuesForUpdateMechanism returns every value of UpdateMechanism.
func PossibleValuesForUpdateMechanism() []string {
	return []string{
		string(UpdateMechanismBuiltIn),
		string(UpdateMechanismScript),
		string(UpdateMechanismExternal),
		string(UpdateMechanismApt),
		string(UpdateMechanismDocker),
	}
}
