// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PostCommandOperationResponse is the result of PostCommand.
type PostCommandOperationResponse struct {
	HttpResponse *http.Response
	Model        *CommandResource
}

// PostCommand calls POST /api/v3/command.
func (c Client) PostCommand(ctx context.Context, input json.RawMessage) (result PostCommandOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusCreated,
		},
		HttpMethod: http.MethodPost,
		Path:       "/api/v3/command",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model CommandResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
