// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// CommandResource is the "CommandResource" schema.
type CommandResource struct {
	Body                *Command        `json:"body,omitempty"`
	ClientUserAgent     string          `json:"clientUserAgent,omitempty"`
	CommandName         string          `json:"commandName,omitempty"`
	Duration            string          `json:"duration,omitempty"`
	Ended               string          `json:"ended,omitempty"`
	Exception           string          `json:"exception,omitempty"`
	Id                  int             `json:"id,omitempty"`
	LastExecutionTime   string          `json:"lastExecutionTime,omitempty"`
	Message             string          `json:"message,omitempty"`
	Name                string          `json:"name,omitempty"`
	Priority            CommandPriority `json:"priority,omitempty"`
	Queued              string          `json:"queued,omitempty"`
	Result              CommandResult   `json:"result,omitempty"`
	SendUpdatesToClient *bool           `json:"sendUpdatesToClient,omitempty"`
	Started             string          `json:"started,omitempty"`
	StateChangeTime     string          `json:"stateChangeTime,omitempty"`
	Status              CommandStatus   `json:"status,omitempty"`
	Trigger             CommandTrigger  `json:"trigger,omitempty"`
	UpdateScheduledTask *bool           `json:"updateScheduledTask,omitempty"`
}
