// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// EpisodeResource is the "EpisodeResource" schema.
type EpisodeResource struct {
	AbsoluteEpisodeNumber      int                  `json:"absoluteEpisodeNumber,omitempty"`
	AirDate                    string               `json:"airDate,omitempty"`
	AirDateUtc                 string               `json:"airDateUtc,omitempty"`
	EndTime                    string               `json:"endTime,omitempty"`
	EpisodeFile                *EpisodeFileResource `json:"episodeFile,omitempty"`
	EpisodeFileId              int                  `json:"episodeFileId,omitempty"`
	EpisodeNumber              int                  `json:"episodeNumber,omitempty"`
	FinaleType                 string               `json:"finaleType,omitempty"`
	GrabDate                   string               `json:"grabDate,omitempty"`
	HasFile                    *bool                `json:"hasFile,omitempty"`
	Id                         int                  `json:"id,omitempty"`
	Images                     []MediaCover         `json:"images,omitzero"`
	LastSearchTime             string               `json:"lastSearchTime,omitempty"`
	Monitored                  *bool                `json:"monitored,omitempty"`
	Overview                   string               `json:"overview,omitempty"`
	Runtime                    int                  `json:"runtime,omitempty"`
	SceneAbsoluteEpisodeNumber int                  `json:"sceneAbsoluteEpisodeNumber,omitempty"`
	SceneEpisodeNumber         int                  `json:"sceneEpisodeNumber,omitempty"`
	SceneSeasonNumber          int                  `json:"sceneSeasonNumber,omitempty"`
	SeasonNumber               int                  `json:"seasonNumber,omitempty"`
	Series                     *SeriesResource      `json:"series,omitempty"`
	SeriesId                   int                  `json:"seriesId,omitempty"`
	Title                      string               `json:"title,omitempty"`
	TvdbId                     int                  `json:"tvdbId,omitempty"`
	UnverifiedSceneNumbering   *bool                `json:"unverifiedSceneNumbering,omitempty"`
}
