// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// Ratings is the "Ratings" schema.
type Ratings struct {
	Value float64 `json:"value,omitempty"`
	Votes int     `json:"votes,omitempty"`
}
