// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// AddSeriesOptions is the "AddSeriesOptions" schema.
type AddSeriesOptions struct {
	IgnoreEpisodesWithFiles      *bool        `json:"ignoreEpisodesWithFiles,omitempty"`
	IgnoreEpisodesWithoutFiles   *bool        `json:"ignoreEpisodesWithoutFiles,omitempty"`
	Monitor                      MonitorTypes `json:"monitor,omitempty"`
	SearchForCutoffUnmetEpisodes *bool        `json:"searchForCutoffUnmetEpisodes,omitempty"`
	SearchForMissingEpisodes     *bool        `json:"searchForMissingEpisodes,omitempty"`
}
