// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// Command is the "Command" schema.
type Command struct {
	ClientUserAgent     string         `json:"clientUserAgent,omitempty"`
	CompletionMessage   string         `json:"completionMessage,omitempty"`
	IsExclusive         *bool          `json:"isExclusive,omitempty"`
	IsLongRunning       *bool          `json:"isLongRunning,omitempty"`
	LastExecutionTime   string         `json:"lastExecutionTime,omitempty"`
	LastStartTime       string         `json:"lastStartTime,omitempty"`
	Name                string         `json:"name,omitempty"`
	RequiresDiskAccess  *bool          `json:"requiresDiskAccess,omitempty"`
	SendUpdatesToClient *bool          `json:"sendUpdatesToClient,omitempty"`
	SuppressMessages    *bool          `json:"suppressMessages,omitempty"`
	Trigger             CommandTrigger `json:"trigger,omitempty"`
	UpdateScheduledTask *bool          `json:"updateScheduledTask,omitempty"`
}
