// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// SelectOption is the "SelectOption" schema.
type SelectOption struct {
	Hint  string `json:"hint,omitempty"`
	Name  string `json:"name,omitempty"`
	Order int    `json:"order,omitempty"`
	Value int    `json:"value,omitempty"`
}
