// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// CustomFormatResource is the "CustomFormatResource" schema.
type CustomFormatResource struct {
	Id                              int                               `json:"id,omitempty"`
	IncludeCustomFormatWhenRenaming *bool                             `json:"includeCustomFormatWhenRenaming,omitempty"`
	Name                            string                            `json:"name,omitempty"`
	Specifications                  []CustomFormatSpecificationSchema `json:"specifications,omitzero"`
}
