// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// ValidationFailure is the "ValidationFailure" schema.
//
// One reason a provider failed its test: the setting at fault and what is wrong with it.
type ValidationFailure struct {
	DetailedDescription string `json:"detailedDescription,omitempty"`
	ErrorCode           string `json:"errorCode,omitempty"`
	ErrorMessage        string `json:"errorMessage,omitempty"`
	InfoLink            string `json:"infoLink,omitempty"`
	IsWarning           *bool  `json:"isWarning,omitempty"`
	PropertyName        string `json:"propertyName,omitempty"`

	// error, warning or info
	Severity string `json:"severity,omitempty"`
}
