// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// TrackedDownloadStatusMessage is the "TrackedDownloadStatusMessage" schema.
type TrackedDownloadStatusMessage struct {
	Messages []string `json:"messages,omitzero"`
	Title    string   `json:"title,omitempty"`
}
