// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// ReleaseEpisodeResource is the "ReleaseEpisodeResource" schema.
type ReleaseEpisodeResource struct {
	AbsoluteEpisodeNumber int    `json:"absoluteEpisodeNumber,omitempty"`
	EpisodeNumber         int    `json:"episodeNumber,omitempty"`
	Id                    int    `json:"id,omitempty"`
	SeasonNumber          int    `json:"seasonNumber,omitempty"`
	Title                 string `json:"title,omitempty"`
}
