// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// CustomFormatSpecificationSchema is the "CustomFormatSpecificationSchema" schema.
type CustomFormatSpecificationSchema struct {
	Fields             []Field                           `json:"fields,omitzero"`
	Id                 int                               `json:"id,omitempty"`
	Implementation     string                            `json:"implementation,omitempty"`
	ImplementationName string                            `json:"implementationName,omitempty"`
	InfoLink           string                            `json:"infoLink,omitempty"`
	Name               string                            `json:"name,omitempty"`
	Negate             *bool                             `json:"negate,omitempty"`
	Presets            []CustomFormatSpecificationSchema `json:"presets,omitzero"`
	Required           *bool                             `json:"required,omitempty"`
}
