// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// QualityProfileQualityItemResource is the "QualityProfileQualityItemResource" schema.
type QualityProfileQualityItemResource struct {
	Allowed *bool                               `json:"allowed,omitempty"`
	Id      int                                 `json:"id,omitempty"`
	Items   []QualityProfileQualityItemResource `json:"items,omitzero"`
	Name    string                              `json:"name,omitempty"`
	Quality *Quality                            `json:"quality,omitempty"`
}
