// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// QualityProfileResource is the "QualityProfileResource" schema.
type QualityProfileResource struct {
	Cutoff                int                                 `json:"cutoff,omitempty"`
	CutoffFormatScore     int                                 `json:"cutoffFormatScore,omitempty"`
	FormatItems           []ProfileFormatItemResource         `json:"formatItems,omitzero"`
	Id                    int                                 `json:"id,omitempty"`
	Items                 []QualityProfileQualityItemResource `json:"items,omitzero"`
	MinFormatScore        int                                 `json:"minFormatScore,omitempty"`
	MinUpgradeFormatScore int                                 `json:"minUpgradeFormatScore,omitempty"`
	Name                  string                              `json:"name,omitempty"`
	UpgradeAllowed        *bool                               `json:"upgradeAllowed,omitempty"`
}
