// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// LanguageProfileItemResource is the "LanguageProfileItemResource" schema.
type LanguageProfileItemResource struct {
	Allowed  *bool     `json:"allowed,omitempty"`
	Id       int       `json:"id,omitempty"`
	Language *Language `json:"language,omitempty"`
}
