// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// SeasonResource is the "SeasonResource" schema.
type SeasonResource struct {
	Images       []MediaCover              `json:"images,omitzero"`
	Monitored    *bool                     `json:"monitored,omitempty"`
	SeasonNumber int                       `json:"seasonNumber,omitempty"`
	Statistics   *SeasonStatisticsResource `json:"statistics,omitempty"`
}
