// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// Field is the "Field" schema.
type Field struct {
	Advanced                    *bool          `json:"advanced,omitempty"`
	HelpLink                    string         `json:"helpLink,omitempty"`
	HelpText                    string         `json:"helpText,omitempty"`
	HelpTextWarning             string         `json:"helpTextWarning,omitempty"`
	Hidden                      string         `json:"hidden,omitempty"`
	IsFloat                     *bool          `json:"isFloat,omitempty"`
	Label                       string         `json:"label,omitempty"`
	Name                        string         `json:"name,omitempty"`
	Order                       int            `json:"order,omitempty"`
	Placeholder                 string         `json:"placeholder,omitempty"`
	Privacy                     PrivacyLevel   `json:"privacy,omitempty"`
	Section                     string         `json:"section,omitempty"`
	SelectOptions               []SelectOption `json:"selectOptions,omitzero"`
	SelectOptionsProviderAction string         `json:"selectOptionsProviderAction,omitempty"`
	Type                        string         `json:"type,omitempty"`
	Unit                        string         `json:"unit,omitempty"`
	Value                       any            `json:"value,omitempty"`
}
