// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// Language is the "Language" schema.
type Language struct {
	Id   int    `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}
