// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// EpisodeResourcePagingResource is the "EpisodeResourcePagingResource" schema.
type EpisodeResourcePagingResource struct {
	Page          int               `json:"page,omitempty"`
	PageSize      int               `json:"pageSize,omitempty"`
	Records       []EpisodeResource `json:"records,omitzero"`
	SortDirection SortDirection     `json:"sortDirection,omitempty"`
	SortKey       string            `json:"sortKey,omitempty"`
	TotalRecords  int               `json:"totalRecords,omitempty"`
}
