// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// ProviderMessage is the "ProviderMessage" schema.
type ProviderMessage struct {
	Message string              `json:"message,omitempty"`
	Type    ProviderMessageType `json:"type,omitempty"`
}
