// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// AlternateTitleResource is the "AlternateTitleResource" schema.
type AlternateTitleResource struct {
	Comment           string `json:"comment,omitempty"`
	SceneOrigin       string `json:"sceneOrigin,omitempty"`
	SceneSeasonNumber int    `json:"sceneSeasonNumber,omitempty"`
	SeasonNumber      int    `json:"seasonNumber,omitempty"`
	Title             string `json:"title,omitempty"`
}
