// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// LogFileResource is the "LogFileResource" schema.
type LogFileResource struct {
	ContentsUrl   string `json:"contentsUrl,omitempty"`
	DownloadUrl   string `json:"downloadUrl,omitempty"`
	Filename      string `json:"filename,omitempty"`
	Id            int    `json:"id,omitempty"`
	LastWriteTime string `json:"lastWriteTime,omitempty"`
}
