// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PutCustomFilterByIdOperationResponse is the result of PutCustomFilterById.
type PutCustomFilterByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *CustomFilterResource
}

// PutCustomFilterById calls PUT /api/v3/customfilter/{id}.
func (c Client) PutCustomFilterById(ctx context.Context, id string, input CustomFilterResource) (result PutCustomFilterByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusAccepted,
		},
		HttpMethod: http.MethodPut,
		Path:       fmt.Sprintf("/api/v3/customfilter/%s", url.PathEscape(id)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model CustomFilterResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
