// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// CustomFilterResource is the "CustomFilterResource" schema.
type CustomFilterResource struct {
	Filters []map[string]any `json:"filters,omitzero"`
	Id      int              `json:"id,omitempty"`
	Label   string           `json:"label,omitempty"`
	Type    string           `json:"type,omitempty"`
}
