// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetCustomFormatOperationResponse is the result of GetCustomFormat.
type GetCustomFormatOperationResponse struct {
	HttpResponse *http.Response
	Model        []CustomFormatResource
}

// GetCustomFormat calls GET /api/v3/customformat.
func (c Client) GetCustomFormat(ctx context.Context) (result GetCustomFormatOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/customformat",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
