// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetCustomFilterOperationResponse is the result of GetCustomFilter.
type GetCustomFilterOperationResponse struct {
	HttpResponse *http.Response
	Model        []CustomFilterResource
}

// GetCustomFilter calls GET /api/v3/customfilter.
func (c Client) GetCustomFilter(ctx context.Context) (result GetCustomFilterOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/customfilter",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
