// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetCustomFilterByIdOperationResponse is the result of GetCustomFilterById.
type GetCustomFilterByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *CustomFilterResource
}

// GetCustomFilterById calls GET /api/v3/customfilter/{id}.
func (c Client) GetCustomFilterById(ctx context.Context, id int) (result GetCustomFilterByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/api/v3/customfilter/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model CustomFilterResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
