// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// CustomFormatBulkResource is the "CustomFormatBulkResource" schema.
type CustomFormatBulkResource struct {
	Ids                             []int `json:"ids,omitzero"`
	IncludeCustomFormatWhenRenaming *bool `json:"includeCustomFormatWhenRenaming,omitempty"`
}
