// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetWantedCutoffOperationResponse is the result of GetWantedCutoff.
type GetWantedCutoffOperationResponse struct {
	HttpResponse *http.Response
	Model        *EpisodeResourcePagingResource
}

// GetWantedCutoffOperationOptions holds the query and header parameters of GetWantedCutoff.
type GetWantedCutoffOperationOptions struct {
	Page               int
	PageSize           int
	SortKey            string
	SortDirection      SortDirection
	IncludeSeries      *bool
	IncludeEpisodeFile *bool
	IncludeImages      *bool
	Monitored          *bool
}

// ToHeaders returns the header parameters the options set.
func (o GetWantedCutoffOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetWantedCutoffOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Page != 0 {
		out.Append("page", strconv.Itoa(o.Page))
	}
	if o.PageSize != 0 {
		out.Append("pageSize", strconv.Itoa(o.PageSize))
	}
	if o.SortKey != "" {
		out.Append("sortKey", o.SortKey)
	}
	if o.SortDirection != "" {
		out.Append("sortDirection", string(o.SortDirection))
	}
	if o.IncludeSeries != nil {
		out.Append("includeSeries", strconv.FormatBool(*o.IncludeSeries))
	}
	if o.IncludeEpisodeFile != nil {
		out.Append("includeEpisodeFile", strconv.FormatBool(*o.IncludeEpisodeFile))
	}
	if o.IncludeImages != nil {
		out.Append("includeImages", strconv.FormatBool(*o.IncludeImages))
	}
	if o.Monitored != nil {
		out.Append("monitored", strconv.FormatBool(*o.Monitored))
	}
	return &out
}

// GetWantedCutoff calls GET /api/v3/wanted/cutoff.
func (c Client) GetWantedCutoff(ctx context.Context, options GetWantedCutoffOperationOptions) (result GetWantedCutoffOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/wanted/cutoff",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model EpisodeResourcePagingResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}

// GetWantedCutoffCompleteResult is every result GetWantedCutoffComplete loaded.
type GetWantedCutoffCompleteResult struct {
	LatestHttpResponse *http.Response
	Items              []EpisodeResource
}

// GetWantedCutoffComplete calls GetWantedCutoff page by page, from options.Page (the first page
// when unset), until every result is loaded. options.PageSize is the page size,
// client.DefaultPageSize when unset.
func (c Client) GetWantedCutoffComplete(ctx context.Context, options GetWantedCutoffOperationOptions) (result GetWantedCutoffCompleteResult, err error) {
	if options.PageSize <= 0 {
		options.PageSize = client.DefaultPageSize
	}
	if options.Page <= 0 {
		options.Page = 1
	}
	for {
		var page GetWantedCutoffOperationResponse
		page, err = c.GetWantedCutoff(ctx, options)
		result.LatestHttpResponse = page.HttpResponse
		if err != nil {
			err = fmt.Errorf("loading results: %w", err)
			return
		}
		if page.Model == nil || len(page.Model.Records) == 0 {
			return
		}
		result.Items = append(result.Items, page.Model.Records...)
		// a short page is the last; so is the page that reaches the total
		if len(page.Model.Records) < options.PageSize || page.Model.TotalRecords > 0 && options.Page*options.PageSize >= page.Model.TotalRecords {
			return
		}
		options.Page++
	}
}
