// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetWantedCutoffByIdOperationResponse is the result of GetWantedCutoffById.
type GetWantedCutoffByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *EpisodeResource
}

// GetWantedCutoffById calls GET /api/v3/wanted/cutoff/{id}.
func (c Client) GetWantedCutoffById(ctx context.Context, id int) (result GetWantedCutoffByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/api/v3/wanted/cutoff/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model EpisodeResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
