// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PutDelayProfileReorderByIdOperationResponse is the result of PutDelayProfileReorderById.
type PutDelayProfileReorderByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        []DelayProfileResource
}

// PutDelayProfileReorderByIdOperationOptions holds the query and header parameters of PutDelayProfileReorderById.
type PutDelayProfileReorderByIdOperationOptions struct {
	After int
}

// ToHeaders returns the header parameters the options set.
func (o PutDelayProfileReorderByIdOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PutDelayProfileReorderByIdOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.After != 0 {
		out.Append("after", strconv.Itoa(o.After))
	}
	return &out
}

// PutDelayProfileReorderById calls PUT /api/v3/delayprofile/reorder/{id}.
func (c Client) PutDelayProfileReorderById(ctx context.Context, id int, options PutDelayProfileReorderByIdOperationOptions) (result PutDelayProfileReorderByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodPut,
		OptionsObject: options,
		Path:          fmt.Sprintf("/api/v3/delayprofile/reorder/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
