// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// DelayProfileResource is the "DelayProfileResource" schema.
type DelayProfileResource struct {
	BypassIfAboveCustomFormatScore *bool            `json:"bypassIfAboveCustomFormatScore,omitempty"`
	BypassIfHighestQuality         *bool            `json:"bypassIfHighestQuality,omitempty"`
	EnableTorrent                  *bool            `json:"enableTorrent,omitempty"`
	EnableUsenet                   *bool            `json:"enableUsenet,omitempty"`
	Id                             int              `json:"id,omitempty"`
	MinimumCustomFormatScore       int              `json:"minimumCustomFormatScore,omitempty"`
	Order                          int              `json:"order,omitempty"`
	PreferredProtocol              DownloadProtocol `json:"preferredProtocol,omitempty"`
	Tags                           []int            `json:"tags,omitzero"`
	TorrentDelay                   int              `json:"torrentDelay,omitempty"`
	UsenetDelay                    int              `json:"usenetDelay,omitempty"`
}
