// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"encoding/json"
	"net/http"
	"testing"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

func TestOperationPutDelayProfileById(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 202, "application/json", "{}")
	result, err := c.PutDelayProfileById(t.Context(), "p/id", DelayProfileResource{})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodPut, "/api/v3/delayprofile/p%2Fid")
	if got := r.Header.Get("Content-Type"); got != "application/json" {
		t.Errorf("Content-Type = %q, want %q", got, "application/json")
	}
	if !json.Valid([]byte(body)) {
		t.Errorf("body = %q, want JSON", body)
	}
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 202 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}
	if result.Model == nil {
		t.Error("the model was not decoded")
	}

	// an answer that does not decode is an error, with the response
	c, _ = newOperationServer(t, 202, "application/json", "<html>")
	result, err = c.PutDelayProfileById(t.Context(), "p/id", DelayProfileResource{})
	if err == nil || client.StatusCode(err) != 0 || result.HttpResponse == nil {
		t.Errorf("an answer that does not decode = %v", err)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.PutDelayProfileById(t.Context(), "p/id", DelayProfileResource{})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
