// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetDiskSpaceOperationResponse is the result of GetDiskSpace.
type GetDiskSpaceOperationResponse struct {
	HttpResponse *http.Response
	Model        []DiskSpaceResource
}

// GetDiskSpace calls GET /api/v3/diskspace.
func (c Client) GetDiskSpace(ctx context.Context) (result GetDiskSpaceOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/diskspace",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
