// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// DiskSpaceResource is the "DiskSpaceResource" schema.
type DiskSpaceResource struct {
	FreeSpace  int64  `json:"freeSpace,omitempty"`
	Id         int    `json:"id,omitempty"`
	Label      string `json:"label,omitempty"`
	Path       string `json:"path,omitempty"`
	TotalSpace int64  `json:"totalSpace,omitempty"`
}
