// Code generated by internal/pandorest; DO NOT EDIT.

// Package sonarr is a typed client for Sonarr 3.0.0, generated by internal/pandorest
// from the definitions in api-definitions/sonarr, which were imported from docs/sonarr-openapi.json.
//
// # Layout
//
// Every operation of the API is a method on Client, in a file of its own named
// <tag>_method_<operation>.go. Each model is in <tag>_model_<model>.go and each
// tag's enums in <tag>_constants.go; a model or enum more than one tag uses is
// under common_. The requests go through the hand-written base client,
// lib/client.
//
// # Calls
//
// A method takes a context, then the path parameters in path order, then the
// request body (input: the model for a JSON body, or an io.Reader and its
// content type for raw bytes), then, when the operation has query or header
// parameters, a <Name>OperationOptions. Unset options are not sent: zero
// values are skipped, a *bool is sent when set, and a list is sent as one
// parameter per element.
//
// It returns a <Name>OperationResponse holding HttpResponse and, when the
// operation answers JSON, Model. HttpResponse is set whenever the server
// answered, including alongside an error, and its body can be read again. An
// operation that answers a file leaves the body unread in
// HttpResponse.Body for the caller to read and close. A status the operation
// does not document is a *client.StatusError; client.IsNotFound recognises a
// 404.
//
// A list operation that pages by page number and page size also has a
// <Name>Complete method that pages through every result.
//
// Dates are strings: Sonarr sends RFC 3339 in UTC ("2026-09-19T13:00:00Z").
//
// # Workarounds
//
// The importer fixed these bugs in the document before generating from it:
//
//   - sonarr-ui-routes
//   - sonarr-undeclared-responses
//   - sonarr-undeclared-write-responses
//   - sonarr-created-accepted
//   - sonarr-test-all-results
//   - sonarr-command-body
//   - sonarr-http-uri-string
//   - sonarr-bulk-update-lists
package sonarr
