// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// DownloadClientResource is the "DownloadClientResource" schema.
type DownloadClientResource struct {
	ConfigContract           string                   `json:"configContract,omitempty"`
	Enable                   *bool                    `json:"enable,omitempty"`
	Fields                   []Field                  `json:"fields,omitzero"`
	Id                       int                      `json:"id,omitempty"`
	Implementation           string                   `json:"implementation,omitempty"`
	ImplementationName       string                   `json:"implementationName,omitempty"`
	InfoLink                 string                   `json:"infoLink,omitempty"`
	Message                  *ProviderMessage         `json:"message,omitempty"`
	Name                     string                   `json:"name,omitempty"`
	Presets                  []DownloadClientResource `json:"presets,omitzero"`
	Priority                 int                      `json:"priority,omitempty"`
	Protocol                 DownloadProtocol         `json:"protocol,omitempty"`
	RemoveCompletedDownloads *bool                    `json:"removeCompletedDownloads,omitempty"`
	RemoveFailedDownloads    *bool                    `json:"removeFailedDownloads,omitempty"`
	Tags                     []int                    `json:"tags,omitzero"`
}
