// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// DownloadClientBulkResource is the "DownloadClientBulkResource" schema.
type DownloadClientBulkResource struct {
	ApplyTags                ApplyTags `json:"applyTags,omitempty"`
	Enable                   *bool     `json:"enable,omitempty"`
	Ids                      []int     `json:"ids,omitzero"`
	Priority                 int       `json:"priority,omitempty"`
	RemoveCompletedDownloads *bool     `json:"removeCompletedDownloads,omitempty"`
	RemoveFailedDownloads    *bool     `json:"removeFailedDownloads,omitempty"`
	Tags                     []int     `json:"tags,omitzero"`
}
