// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PutDownloadClientBulkOperationResponse is the result of PutDownloadClientBulk.
type PutDownloadClientBulkOperationResponse struct {
	HttpResponse *http.Response
	Model        *DownloadClientResource
}

// PutDownloadClientBulk calls PUT /api/v3/downloadclient/bulk.
func (c Client) PutDownloadClientBulk(ctx context.Context, input DownloadClientBulkResource) (result PutDownloadClientBulkOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusAccepted,
		},
		HttpMethod: http.MethodPut,
		Path:       "/api/v3/downloadclient/bulk",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model DownloadClientResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
