// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetDownloadClientByIdOperationResponse is the result of GetDownloadClientById.
type GetDownloadClientByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *DownloadClientResource
}

// GetDownloadClientById calls GET /api/v3/downloadclient/{id}.
func (c Client) GetDownloadClientById(ctx context.Context, id int) (result GetDownloadClientByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/api/v3/downloadclient/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model DownloadClientResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
