// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PutEpisodeMonitorOperationResponse is the result of PutEpisodeMonitor.
type PutEpisodeMonitorOperationResponse struct {
	HttpResponse *http.Response
	Model        []EpisodeResource
}

// PutEpisodeMonitorOperationOptions holds the query and header parameters of PutEpisodeMonitor.
type PutEpisodeMonitorOperationOptions struct {
	IncludeImages *bool
}

// ToHeaders returns the header parameters the options set.
func (o PutEpisodeMonitorOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PutEpisodeMonitorOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.IncludeImages != nil {
		out.Append("includeImages", strconv.FormatBool(*o.IncludeImages))
	}
	return &out
}

// PutEpisodeMonitor calls PUT /api/v3/episode/monitor.
func (c Client) PutEpisodeMonitor(ctx context.Context, input EpisodesMonitoredResource, options PutEpisodeMonitorOperationOptions) (result PutEpisodeMonitorOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusAccepted,
		},
		HttpMethod:    http.MethodPut,
		OptionsObject: options,
		Path:          "/api/v3/episode/monitor",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
