// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetEpisodeOperationResponse is the result of GetEpisode.
type GetEpisodeOperationResponse struct {
	HttpResponse *http.Response
	Model        []EpisodeResource
}

// GetEpisodeOperationOptions holds the query and header parameters of GetEpisode.
type GetEpisodeOperationOptions struct {
	SeriesId           int
	SeasonNumber       int
	EpisodeIds         []int
	EpisodeFileId      int
	IncludeSeries      *bool
	IncludeEpisodeFile *bool
	IncludeImages      *bool
}

// ToHeaders returns the header parameters the options set.
func (o GetEpisodeOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetEpisodeOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.SeriesId != 0 {
		out.Append("seriesId", strconv.Itoa(o.SeriesId))
	}
	if o.SeasonNumber != 0 {
		out.Append("seasonNumber", strconv.Itoa(o.SeasonNumber))
	}
	for _, v := range o.EpisodeIds {
		out.Append("episodeIds", strconv.Itoa(v))
	}
	if o.EpisodeFileId != 0 {
		out.Append("episodeFileId", strconv.Itoa(o.EpisodeFileId))
	}
	if o.IncludeSeries != nil {
		out.Append("includeSeries", strconv.FormatBool(*o.IncludeSeries))
	}
	if o.IncludeEpisodeFile != nil {
		out.Append("includeEpisodeFile", strconv.FormatBool(*o.IncludeEpisodeFile))
	}
	if o.IncludeImages != nil {
		out.Append("includeImages", strconv.FormatBool(*o.IncludeImages))
	}
	return &out
}

// GetEpisode calls GET /api/v3/episode.
func (c Client) GetEpisode(ctx context.Context, options GetEpisodeOperationOptions) (result GetEpisodeOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/episode",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
