// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PutEpisodeByIdOperationResponse is the result of PutEpisodeById.
type PutEpisodeByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *EpisodeResource
}

// PutEpisodeById calls PUT /api/v3/episode/{id}.
func (c Client) PutEpisodeById(ctx context.Context, id int, input EpisodeResource) (result PutEpisodeByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusAccepted,
		},
		HttpMethod: http.MethodPut,
		Path:       fmt.Sprintf("/api/v3/episode/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model EpisodeResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
