// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetEpisodeFileOperationResponse is the result of GetEpisodeFile.
type GetEpisodeFileOperationResponse struct {
	HttpResponse *http.Response
	Model        []EpisodeFileResource
}

// GetEpisodeFileOperationOptions holds the query and header parameters of GetEpisodeFile.
type GetEpisodeFileOperationOptions struct {
	SeriesId       int
	EpisodeFileIds []int
}

// ToHeaders returns the header parameters the options set.
func (o GetEpisodeFileOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetEpisodeFileOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.SeriesId != 0 {
		out.Append("seriesId", strconv.Itoa(o.SeriesId))
	}
	for _, v := range o.EpisodeFileIds {
		out.Append("episodeFileIds", strconv.Itoa(v))
	}
	return &out
}

// GetEpisodeFile calls GET /api/v3/episodefile.
func (c Client) GetEpisodeFile(ctx context.Context, options GetEpisodeFileOperationOptions) (result GetEpisodeFileOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/episodefile",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
