// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// EpisodeFileListResource is the "EpisodeFileListResource" schema.
type EpisodeFileListResource struct {
	EpisodeFileIds []int         `json:"episodeFileIds,omitzero"`
	Languages      []Language    `json:"languages,omitzero"`
	Quality        *QualityModel `json:"quality,omitempty"`
	ReleaseGroup   string        `json:"releaseGroup,omitempty"`
	SceneName      string        `json:"sceneName,omitempty"`
}
