// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// EpisodesMonitoredResource is the "EpisodesMonitoredResource" schema.
type EpisodesMonitoredResource struct {
	EpisodeIds []int `json:"episodeIds,omitzero"`
	Monitored  *bool `json:"monitored,omitempty"`
}
