// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PutEpisodeFileBulkOperationResponse is the result of PutEpisodeFileBulk.
type PutEpisodeFileBulkOperationResponse struct {
	HttpResponse *http.Response
	Model        []EpisodeFileResource
}

// PutEpisodeFileBulk calls PUT /api/v3/episodefile/bulk.
func (c Client) PutEpisodeFileBulk(ctx context.Context, input []EpisodeFileResource) (result PutEpisodeFileBulkOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusAccepted,
		},
		HttpMethod: http.MethodPut,
		Path:       "/api/v3/episodefile/bulk",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
