// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"net/http"
	"testing"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

func TestOperationGetEpisode(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 200, "application/json", "[{}]")
	result, err := c.GetEpisode(t.Context(), GetEpisodeOperationOptions{
		SeriesId:           7,
		SeasonNumber:       7,
		EpisodeIds:         []int{1, 2},
		EpisodeFileId:      7,
		IncludeSeries:      new(true),
		IncludeEpisodeFile: new(true),
		IncludeImages:      new(true),
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodGet, "/api/v3/episode")
	expectQuery(t, r, "seriesId", "7")
	expectQuery(t, r, "seasonNumber", "7")
	expectQuery(t, r, "episodeIds", "1", "2")
	expectQuery(t, r, "episodeFileId", "7")
	expectQuery(t, r, "includeSeries", "true")
	expectQuery(t, r, "includeEpisodeFile", "true")
	expectQuery(t, r, "includeImages", "true")
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 200 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}
	if result.Model == nil {
		t.Error("the model was not decoded")
	}

	// an answer that does not decode is an error, with the response
	c, _ = newOperationServer(t, 200, "application/json", "<html>")
	result, err = c.GetEpisode(t.Context(), GetEpisodeOperationOptions{
		SeriesId:           7,
		SeasonNumber:       7,
		EpisodeIds:         []int{1, 2},
		EpisodeFileId:      7,
		IncludeSeries:      new(true),
		IncludeEpisodeFile: new(true),
		IncludeImages:      new(true),
	})
	if err == nil || client.StatusCode(err) != 0 || result.HttpResponse == nil {
		t.Errorf("an answer that does not decode = %v", err)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.GetEpisode(t.Context(), GetEpisodeOperationOptions{
		SeriesId:           7,
		SeasonNumber:       7,
		EpisodeIds:         []int{1, 2},
		EpisodeFileId:      7,
		IncludeSeries:      new(true),
		IncludeEpisodeFile: new(true),
		IncludeImages:      new(true),
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
