// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"encoding/json"
	"net/http"
	"strconv"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetFileSystemOperationResponse is the result of GetFileSystem.
type GetFileSystemOperationResponse struct {
	HttpResponse *http.Response
	Model        json.RawMessage
}

// GetFileSystemOperationOptions holds the query and header parameters of GetFileSystem.
type GetFileSystemOperationOptions struct {
	Path                               string
	IncludeFiles                       *bool
	AllowFoldersWithoutTrailingSlashes *bool
}

// ToHeaders returns the header parameters the options set.
func (o GetFileSystemOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetFileSystemOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Path != "" {
		out.Append("path", o.Path)
	}
	if o.IncludeFiles != nil {
		out.Append("includeFiles", strconv.FormatBool(*o.IncludeFiles))
	}
	if o.AllowFoldersWithoutTrailingSlashes != nil {
		out.Append("allowFoldersWithoutTrailingSlashes", strconv.FormatBool(*o.AllowFoldersWithoutTrailingSlashes))
	}
	return &out
}

// GetFileSystem calls GET /api/v3/filesystem.
func (c Client) GetFileSystem(ctx context.Context, options GetFileSystemOperationOptions) (result GetFileSystemOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/filesystem",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
