// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetFileSystemMediaFilesOperationResponse is the result of GetFileSystemMediaFiles.
type GetFileSystemMediaFilesOperationResponse struct {
	HttpResponse *http.Response
	Model        json.RawMessage
}

// GetFileSystemMediaFilesOperationOptions holds the query and header parameters of GetFileSystemMediaFiles.
type GetFileSystemMediaFilesOperationOptions struct {
	Path string
}

// ToHeaders returns the header parameters the options set.
func (o GetFileSystemMediaFilesOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetFileSystemMediaFilesOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Path != "" {
		out.Append("path", o.Path)
	}
	return &out
}

// GetFileSystemMediaFiles calls GET /api/v3/filesystem/mediafiles.
func (c Client) GetFileSystemMediaFiles(ctx context.Context, options GetFileSystemMediaFilesOperationOptions) (result GetFileSystemMediaFilesOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/filesystem/mediafiles",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
