// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// HealthCheckResult is the "HealthCheckResult" enum.
type HealthCheckResult string

// Values of HealthCheckResult.
const (
	HealthCheckResultOk      HealthCheckResult = "ok"
	HealthCheckResultNotice  HealthCheckResult = "notice"
	HealthCheckResultWarning HealthCheckResult = "warning"
	HealthCheckResultError   HealthCheckResult = "error"
)

// PossibleValuesForHealthCheckResult returns every value of HealthCheckResult.
func PossibleValuesForHealthCheckResult() []string {
	return []string{
		string(HealthCheckResultOk),
		string(HealthCheckResultNotice),
		string(HealthCheckResultWarning),
		string(HealthCheckResultError),
	}
}
