// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// HealthResource is the "HealthResource" schema.
type HealthResource struct {
	Id      int               `json:"id,omitempty"`
	Message string            `json:"message,omitempty"`
	Source  string            `json:"source,omitempty"`
	Type    HealthCheckResult `json:"type,omitempty"`
	WikiUrl string            `json:"wikiUrl,omitempty"`
}
