// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetHistorySeriesOperationResponse is the result of GetHistorySeries.
type GetHistorySeriesOperationResponse struct {
	HttpResponse *http.Response
	Model        []HistoryResource
}

// GetHistorySeriesOperationOptions holds the query and header parameters of GetHistorySeries.
type GetHistorySeriesOperationOptions struct {
	SeriesId       int
	SeasonNumber   int
	EventType      EpisodeHistoryEventType
	IncludeSeries  *bool
	IncludeEpisode *bool
}

// ToHeaders returns the header parameters the options set.
func (o GetHistorySeriesOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetHistorySeriesOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.SeriesId != 0 {
		out.Append("seriesId", strconv.Itoa(o.SeriesId))
	}
	if o.SeasonNumber != 0 {
		out.Append("seasonNumber", strconv.Itoa(o.SeasonNumber))
	}
	if o.EventType != "" {
		out.Append("eventType", string(o.EventType))
	}
	if o.IncludeSeries != nil {
		out.Append("includeSeries", strconv.FormatBool(*o.IncludeSeries))
	}
	if o.IncludeEpisode != nil {
		out.Append("includeEpisode", strconv.FormatBool(*o.IncludeEpisode))
	}
	return &out
}

// GetHistorySeries calls GET /api/v3/history/series.
func (c Client) GetHistorySeries(ctx context.Context, options GetHistorySeriesOperationOptions) (result GetHistorySeriesOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/history/series",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
