// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// HistoryResource is the "HistoryResource" schema.
type HistoryResource struct {
	CustomFormatScore   int                     `json:"customFormatScore,omitempty"`
	CustomFormats       []CustomFormatResource  `json:"customFormats,omitzero"`
	Data                map[string]string       `json:"data,omitzero"`
	Date                string                  `json:"date,omitempty"`
	DownloadId          string                  `json:"downloadId,omitempty"`
	Episode             *EpisodeResource        `json:"episode,omitempty"`
	EpisodeId           int                     `json:"episodeId,omitempty"`
	EventType           EpisodeHistoryEventType `json:"eventType,omitempty"`
	Id                  int                     `json:"id,omitempty"`
	Languages           []Language              `json:"languages,omitzero"`
	Quality             *QualityModel           `json:"quality,omitempty"`
	QualityCutoffNotMet *bool                   `json:"qualityCutoffNotMet,omitempty"`
	Series              *SeriesResource         `json:"series,omitempty"`
	SeriesId            int                     `json:"seriesId,omitempty"`
	SourceTitle         string                  `json:"sourceTitle,omitempty"`
}
