// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// EpisodeHistoryEventType is the "EpisodeHistoryEventType" enum.
type EpisodeHistoryEventType string

// Values of EpisodeHistoryEventType.
const (
	EpisodeHistoryEventTypeUnknown                EpisodeHistoryEventType = "unknown"
	EpisodeHistoryEventTypeGrabbed                EpisodeHistoryEventType = "grabbed"
	EpisodeHistoryEventTypeSeriesFolderImported   EpisodeHistoryEventType = "seriesFolderImported"
	EpisodeHistoryEventTypeDownloadFolderImported EpisodeHistoryEventType = "downloadFolderImported"
	EpisodeHistoryEventTypeDownloadFailed         EpisodeHistoryEventType = "downloadFailed"
	EpisodeHistoryEventTypeEpisodeFileDeleted     EpisodeHistoryEventType = "episodeFileDeleted"
	EpisodeHistoryEventTypeEpisodeFileRenamed     EpisodeHistoryEventType = "episodeFileRenamed"
	EpisodeHistoryEventTypeDownloadIgnored        EpisodeHistoryEventType = "downloadIgnored"
)

// PossibleValuesForEpisodeHistoryEventType returns every value of EpisodeHistoryEventType.
func PossibleValuesForEpisodeHistoryEventType() []string {
	return []string{
		string(EpisodeHistoryEventTypeUnknown),
		string(EpisodeHistoryEventTypeGrabbed),
		string(EpisodeHistoryEventTypeSeriesFolderImported),
		string(EpisodeHistoryEventTypeDownloadFolderImported),
		string(EpisodeHistoryEventTypeDownloadFailed),
		string(EpisodeHistoryEventTypeEpisodeFileDeleted),
		string(EpisodeHistoryEventTypeEpisodeFileRenamed),
		string(EpisodeHistoryEventTypeDownloadIgnored),
	}
}
