// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// HistoryResourcePagingResource is the "HistoryResourcePagingResource" schema.
type HistoryResourcePagingResource struct {
	Page          int               `json:"page,omitempty"`
	PageSize      int               `json:"pageSize,omitempty"`
	Records       []HistoryResource `json:"records,omitzero"`
	SortDirection SortDirection     `json:"sortDirection,omitempty"`
	SortKey       string            `json:"sortKey,omitempty"`
	TotalRecords  int               `json:"totalRecords,omitempty"`
}
