// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// AuthenticationRequiredType is the "AuthenticationRequiredType" enum.
type AuthenticationRequiredType string

// Values of AuthenticationRequiredType.
const (
	AuthenticationRequiredTypeEnabled                   AuthenticationRequiredType = "enabled"
	AuthenticationRequiredTypeDisabledForLocalAddresses AuthenticationRequiredType = "disabledForLocalAddresses"
)

// PossibleValuesForAuthenticationRequiredType returns every value of AuthenticationRequiredType.
func PossibleValuesForAuthenticationRequiredType() []string {
	return []string{
		string(AuthenticationRequiredTypeEnabled),
		string(AuthenticationRequiredTypeDisabledForLocalAddresses),
	}
}

// CertificateValidationType is the "CertificateValidationType" enum.
type CertificateValidationType string

// Values of CertificateValidationType.
const (
	CertificateValidationTypeEnabled                   CertificateValidationType = "enabled"
	CertificateValidationTypeDisabledForLocalAddresses CertificateValidationType = "disabledForLocalAddresses"
	CertificateValidationTypeDisabled                  CertificateValidationType = "disabled"
)

// PossibleValuesForCertificateValidationType returns every value of CertificateValidationType.
func PossibleValuesForCertificateValidationType() []string {
	return []string{
		string(CertificateValidationTypeEnabled),
		string(CertificateValidationTypeDisabledForLocalAddresses),
		string(CertificateValidationTypeDisabled),
	}
}

// ProxyType is the "ProxyType" enum.
type ProxyType string

// Values of ProxyType.
const (
	ProxyTypeHttp   ProxyType = "http"
	ProxyTypeSocks4 ProxyType = "socks4"
	ProxyTypeSocks5 ProxyType = "socks5"
)

// PossibleValuesForProxyType returns every value of ProxyType.
func PossibleValuesForProxyType() []string {
	return []string{
		string(ProxyTypeHttp),
		string(ProxyTypeSocks4),
		string(ProxyTypeSocks5),
	}
}
