// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// HostConfigResource is the "HostConfigResource" schema.
type HostConfigResource struct {
	AllowedHosts              string                     `json:"allowedHosts,omitempty"`
	AnalyticsEnabled          *bool                      `json:"analyticsEnabled,omitempty"`
	ApiKey                    string                     `json:"apiKey,omitempty"`
	ApplicationUrl            string                     `json:"applicationUrl,omitempty"`
	AuthenticationMethod      AuthenticationType         `json:"authenticationMethod,omitempty"`
	AuthenticationRequired    AuthenticationRequiredType `json:"authenticationRequired,omitempty"`
	BackupFolder              string                     `json:"backupFolder,omitempty"`
	BackupInterval            int                        `json:"backupInterval,omitempty"`
	BackupRetention           int                        `json:"backupRetention,omitempty"`
	BindAddress               string                     `json:"bindAddress,omitempty"`
	Branch                    string                     `json:"branch,omitempty"`
	CertificateValidation     CertificateValidationType  `json:"certificateValidation,omitempty"`
	ConsoleLogLevel           string                     `json:"consoleLogLevel,omitempty"`
	EnableSsl                 *bool                      `json:"enableSsl,omitempty"`
	Id                        int                        `json:"id,omitempty"`
	InstanceName              string                     `json:"instanceName,omitempty"`
	LaunchBrowser             *bool                      `json:"launchBrowser,omitempty"`
	LogLevel                  string                     `json:"logLevel,omitempty"`
	LogSizeLimit              int                        `json:"logSizeLimit,omitempty"`
	Password                  string                     `json:"password,omitempty"`
	PasswordConfirmation      string                     `json:"passwordConfirmation,omitempty"`
	Port                      int                        `json:"port,omitempty"`
	ProxyBypassFilter         string                     `json:"proxyBypassFilter,omitempty"`
	ProxyBypassLocalAddresses *bool                      `json:"proxyBypassLocalAddresses,omitempty"`
	ProxyEnabled              *bool                      `json:"proxyEnabled,omitempty"`
	ProxyHostname             string                     `json:"proxyHostname,omitempty"`
	ProxyPassword             string                     `json:"proxyPassword,omitempty"`
	ProxyPort                 int                        `json:"proxyPort,omitempty"`
	ProxyType                 ProxyType                  `json:"proxyType,omitempty"`
	ProxyUsername             string                     `json:"proxyUsername,omitempty"`
	SslCertPassword           string                     `json:"sslCertPassword,omitempty"`
	SslCertPath               string                     `json:"sslCertPath,omitempty"`
	SslPort                   int                        `json:"sslPort,omitempty"`
	TrustCgnatIpAddresses     *bool                      `json:"trustCgnatIpAddresses,omitempty"`
	TrustedNetworks           string                     `json:"trustedNetworks,omitempty"`
	UpdateAutomatically       *bool                      `json:"updateAutomatically,omitempty"`
	UpdateMechanism           UpdateMechanism            `json:"updateMechanism,omitempty"`
	UpdateScriptPath          string                     `json:"updateScriptPath,omitempty"`
	UrlBase                   string                     `json:"urlBase,omitempty"`
	Username                  string                     `json:"username,omitempty"`
}
