// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// HostConfigResource is the "HostConfigResource" schema.
type HostConfigResource struct {
	AllowedHosts              string                     `json:"allowedHosts"`
	AnalyticsEnabled          *bool                      `json:"analyticsEnabled,omitempty"`
	ApiKey                    string                     `json:"apiKey"`
	ApplicationUrl            string                     `json:"applicationUrl"`
	AuthenticationMethod      AuthenticationType         `json:"authenticationMethod,omitempty"`
	AuthenticationRequired    AuthenticationRequiredType `json:"authenticationRequired,omitempty"`
	BackupFolder              string                     `json:"backupFolder"`
	BackupInterval            int                        `json:"backupInterval"`
	BackupRetention           int                        `json:"backupRetention"`
	BindAddress               string                     `json:"bindAddress"`
	Branch                    string                     `json:"branch"`
	CertificateValidation     CertificateValidationType  `json:"certificateValidation,omitempty"`
	ConsoleLogLevel           string                     `json:"consoleLogLevel"`
	EnableSsl                 *bool                      `json:"enableSsl,omitempty"`
	Id                        int                        `json:"id"`
	InstanceName              string                     `json:"instanceName"`
	LaunchBrowser             *bool                      `json:"launchBrowser,omitempty"`
	LogLevel                  string                     `json:"logLevel"`
	LogSizeLimit              int                        `json:"logSizeLimit"`
	Password                  string                     `json:"password"`
	PasswordConfirmation      string                     `json:"passwordConfirmation"`
	Port                      int                        `json:"port"`
	ProxyBypassFilter         string                     `json:"proxyBypassFilter"`
	ProxyBypassLocalAddresses *bool                      `json:"proxyBypassLocalAddresses,omitempty"`
	ProxyEnabled              *bool                      `json:"proxyEnabled,omitempty"`
	ProxyHostname             string                     `json:"proxyHostname"`
	ProxyPassword             string                     `json:"proxyPassword"`
	ProxyPort                 int                        `json:"proxyPort"`
	ProxyType                 ProxyType                  `json:"proxyType,omitempty"`
	ProxyUsername             string                     `json:"proxyUsername"`
	SslCertPassword           string                     `json:"sslCertPassword"`
	SslCertPath               string                     `json:"sslCertPath"`
	SslPort                   int                        `json:"sslPort"`
	TrustCgnatIpAddresses     *bool                      `json:"trustCgnatIpAddresses,omitempty"`
	TrustedNetworks           string                     `json:"trustedNetworks"`
	UpdateAutomatically       *bool                      `json:"updateAutomatically,omitempty"`
	UpdateMechanism           UpdateMechanism            `json:"updateMechanism,omitempty"`
	UpdateScriptPath          string                     `json:"updateScriptPath"`
	UrlBase                   string                     `json:"urlBase"`
	Username                  string                     `json:"username"`
}
