// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// DeleteImportListBulkOperationResponse is the result of DeleteImportListBulk.
type DeleteImportListBulkOperationResponse struct {
	HttpResponse *http.Response
}

// DeleteImportListBulk calls DELETE /api/v3/importlist/bulk.
func (c Client) DeleteImportListBulk(ctx context.Context, input ImportListBulkResource) (result DeleteImportListBulkOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodDelete,
		Path:       "/api/v3/importlist/bulk",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
