// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// ImportListResource is the "ImportListResource" schema.
type ImportListResource struct {
	ConfigContract           string               `json:"configContract,omitempty"`
	EnableAutomaticAdd       *bool                `json:"enableAutomaticAdd,omitempty"`
	Fields                   []Field              `json:"fields,omitzero"`
	Id                       int                  `json:"id,omitempty"`
	Implementation           string               `json:"implementation,omitempty"`
	ImplementationName       string               `json:"implementationName,omitempty"`
	InfoLink                 string               `json:"infoLink,omitempty"`
	ListOrder                int                  `json:"listOrder,omitempty"`
	ListType                 ImportListType       `json:"listType,omitempty"`
	Message                  *ProviderMessage     `json:"message,omitempty"`
	MinRefreshInterval       string               `json:"minRefreshInterval,omitempty"`
	MonitorNewItems          NewItemMonitorTypes  `json:"monitorNewItems,omitempty"`
	Name                     string               `json:"name,omitempty"`
	Presets                  []ImportListResource `json:"presets,omitzero"`
	QualityProfileId         int                  `json:"qualityProfileId,omitempty"`
	RootFolderPath           string               `json:"rootFolderPath,omitempty"`
	SearchForMissingEpisodes *bool                `json:"searchForMissingEpisodes,omitempty"`
	SeasonFolder             *bool                `json:"seasonFolder,omitempty"`
	SeriesType               SeriesTypes          `json:"seriesType,omitempty"`
	ShouldMonitor            MonitorTypes         `json:"shouldMonitor,omitempty"`
	Tags                     []int                `json:"tags,omitzero"`
}
