// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetImportListExclusionByIdOperationResponse is the result of GetImportListExclusionById.
type GetImportListExclusionByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *ImportListExclusionResource
}

// GetImportListExclusionById calls GET /api/v3/importlistexclusion/{id}.
func (c Client) GetImportListExclusionById(ctx context.Context, id int) (result GetImportListExclusionByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/api/v3/importlistexclusion/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model ImportListExclusionResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
