// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// ImportListType is the "ImportListType" enum.
type ImportListType string

// Values of ImportListType.
const (
	ImportListTypeProgram  ImportListType = "program"
	ImportListTypePlex     ImportListType = "plex"
	ImportListTypeTrakt    ImportListType = "trakt"
	ImportListTypeSimkl    ImportListType = "simkl"
	ImportListTypeOther    ImportListType = "other"
	ImportListTypeAdvanced ImportListType = "advanced"
)

// PossibleValuesForImportListType returns every value of ImportListType.
func PossibleValuesForImportListType() []string {
	return []string{
		string(ImportListTypeProgram),
		string(ImportListTypePlex),
		string(ImportListTypeTrakt),
		string(ImportListTypeSimkl),
		string(ImportListTypeOther),
		string(ImportListTypeAdvanced),
	}
}
