// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// ImportListExclusionBulkResource is the "ImportListExclusionBulkResource" schema.
type ImportListExclusionBulkResource struct {
	Ids []int `json:"ids,omitzero"`
}
