// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// ImportListExclusionResource is the "ImportListExclusionResource" schema.
type ImportListExclusionResource struct {
	Id     int    `json:"id,omitempty"`
	Title  string `json:"title,omitempty"`
	TvdbId int    `json:"tvdbId,omitempty"`
}
