// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// ImportListExclusionResourcePagingResource is the "ImportListExclusionResourcePagingResource" schema.
type ImportListExclusionResourcePagingResource struct {
	Page          int                           `json:"page,omitempty"`
	PageSize      int                           `json:"pageSize,omitempty"`
	Records       []ImportListExclusionResource `json:"records,omitzero"`
	SortDirection SortDirection                 `json:"sortDirection,omitempty"`
	SortKey       string                        `json:"sortKey,omitempty"`
	TotalRecords  int                           `json:"totalRecords,omitempty"`
}
