// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// ImportListConfigResource is the "ImportListConfigResource" schema.
type ImportListConfigResource struct {
	Id            int               `json:"id,omitempty"`
	ListSyncLevel ListSyncLevelType `json:"listSyncLevel,omitempty"`
	ListSyncTag   int               `json:"listSyncTag,omitempty"`
}
