// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PostImportListExclusionOperationResponse is the result of PostImportListExclusion.
type PostImportListExclusionOperationResponse struct {
	HttpResponse *http.Response
	Model        *ImportListExclusionResource
}

// PostImportListExclusion calls POST /api/v3/importlistexclusion.
func (c Client) PostImportListExclusion(ctx context.Context, input ImportListExclusionResource) (result PostImportListExclusionOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusCreated,
		},
		HttpMethod: http.MethodPost,
		Path:       "/api/v3/importlistexclusion",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model ImportListExclusionResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
