// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetImportListExclusionOperationResponse is the result of GetImportListExclusion.
type GetImportListExclusionOperationResponse struct {
	HttpResponse *http.Response
	Model        []ImportListExclusionResource
}

// GetImportListExclusion calls GET /api/v3/importlistexclusion.
//
// Deprecated: the document marks this operation deprecated.
func (c Client) GetImportListExclusion(ctx context.Context) (result GetImportListExclusionOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/importlistexclusion",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
