// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetConfigImportListByIdOperationResponse is the result of GetConfigImportListById.
type GetConfigImportListByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *ImportListConfigResource
}

// GetConfigImportListById calls GET /api/v3/config/importlist/{id}.
func (c Client) GetConfigImportListById(ctx context.Context, id int) (result GetConfigImportListByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/api/v3/config/importlist/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model ImportListConfigResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
