// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// DeleteImportListByIdOperationResponse is the result of DeleteImportListById.
type DeleteImportListByIdOperationResponse struct {
	HttpResponse *http.Response
}

// DeleteImportListById calls DELETE /api/v3/importlist/{id}.
func (c Client) DeleteImportListById(ctx context.Context, id int) (result DeleteImportListByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodDelete,
		Path:       fmt.Sprintf("/api/v3/importlist/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
