// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// ListSyncLevelType is the "ListSyncLevelType" enum.
type ListSyncLevelType string

// Values of ListSyncLevelType.
const (
	ListSyncLevelTypeDisabled         ListSyncLevelType = "disabled"
	ListSyncLevelTypeLogOnly          ListSyncLevelType = "logOnly"
	ListSyncLevelTypeKeepAndUnmonitor ListSyncLevelType = "keepAndUnmonitor"
	ListSyncLevelTypeKeepAndTag       ListSyncLevelType = "keepAndTag"
)

// PossibleValuesForListSyncLevelType returns every value of ListSyncLevelType.
func PossibleValuesForListSyncLevelType() []string {
	return []string{
		string(ListSyncLevelTypeDisabled),
		string(ListSyncLevelTypeLogOnly),
		string(ListSyncLevelTypeKeepAndUnmonitor),
		string(ListSyncLevelTypeKeepAndTag),
	}
}
