// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetConfigImportListOperationResponse is the result of GetConfigImportList.
type GetConfigImportListOperationResponse struct {
	HttpResponse *http.Response
	Model        *ImportListConfigResource
}

// GetConfigImportList calls GET /api/v3/config/importlist.
func (c Client) GetConfigImportList(ctx context.Context) (result GetConfigImportListOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/config/importlist",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model ImportListConfigResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
