// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// IndexerResource is the "IndexerResource" schema.
type IndexerResource struct {
	ConfigContract                      string            `json:"configContract,omitempty"`
	DownloadClientId                    int               `json:"downloadClientId,omitempty"`
	EnableAutomaticSearch               *bool             `json:"enableAutomaticSearch,omitempty"`
	EnableInteractiveSearch             *bool             `json:"enableInteractiveSearch,omitempty"`
	EnableRss                           *bool             `json:"enableRss,omitempty"`
	Fields                              []Field           `json:"fields,omitzero"`
	Id                                  int               `json:"id,omitempty"`
	Implementation                      string            `json:"implementation,omitempty"`
	ImplementationName                  string            `json:"implementationName,omitempty"`
	InfoLink                            string            `json:"infoLink,omitempty"`
	Message                             *ProviderMessage  `json:"message,omitempty"`
	Name                                string            `json:"name,omitempty"`
	Presets                             []IndexerResource `json:"presets,omitzero"`
	Priority                            int               `json:"priority,omitempty"`
	Protocol                            DownloadProtocol  `json:"protocol,omitempty"`
	SeasonSearchMaximumSingleEpisodeAge int               `json:"seasonSearchMaximumSingleEpisodeAge,omitempty"`
	SupportsRss                         *bool             `json:"supportsRss,omitempty"`
	SupportsSearch                      *bool             `json:"supportsSearch,omitempty"`
	Tags                                []int             `json:"tags,omitzero"`
}
