// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PostIndexerTestOperationResponse is the result of PostIndexerTest.
type PostIndexerTestOperationResponse struct {
	HttpResponse *http.Response
}

// PostIndexerTestOperationOptions holds the query and header parameters of PostIndexerTest.
type PostIndexerTestOperationOptions struct {
	ForceTest *bool
}

// ToHeaders returns the header parameters the options set.
func (o PostIndexerTestOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PostIndexerTestOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.ForceTest != nil {
		out.Append("forceTest", strconv.FormatBool(*o.ForceTest))
	}
	return &out
}

// PostIndexerTest calls POST /api/v3/indexer/test.
func (c Client) PostIndexerTest(ctx context.Context, input IndexerResource, options PostIndexerTestOperationOptions) (result PostIndexerTestOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          "/api/v3/indexer/test",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
