// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetConfigIndexerOperationResponse is the result of GetConfigIndexer.
type GetConfigIndexerOperationResponse struct {
	HttpResponse *http.Response
	Model        *IndexerConfigResource
}

// GetConfigIndexer calls GET /api/v3/config/indexer.
func (c Client) GetConfigIndexer(ctx context.Context) (result GetConfigIndexerOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/config/indexer",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model IndexerConfigResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
