// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// IndexerFlagResource is the "IndexerFlagResource" schema.
type IndexerFlagResource struct {
	Id        int    `json:"id,omitempty"`
	Name      string `json:"name,omitempty"`
	NameLower string `json:"nameLower,omitempty"`
}
