// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// DeleteIndexerBulkOperationResponse is the result of DeleteIndexerBulk.
type DeleteIndexerBulkOperationResponse struct {
	HttpResponse *http.Response
}

// DeleteIndexerBulk calls DELETE /api/v3/indexer/bulk.
func (c Client) DeleteIndexerBulk(ctx context.Context, input IndexerBulkResource) (result DeleteIndexerBulkOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodDelete,
		Path:       "/api/v3/indexer/bulk",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
