// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PostIndexerOperationResponse is the result of PostIndexer.
type PostIndexerOperationResponse struct {
	HttpResponse *http.Response
	Model        *IndexerResource
}

// PostIndexerOperationOptions holds the query and header parameters of PostIndexer.
type PostIndexerOperationOptions struct {
	ForceSave *bool
}

// ToHeaders returns the header parameters the options set.
func (o PostIndexerOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PostIndexerOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.ForceSave != nil {
		out.Append("forceSave", strconv.FormatBool(*o.ForceSave))
	}
	return &out
}

// PostIndexer calls POST /api/v3/indexer.
func (c Client) PostIndexer(ctx context.Context, input IndexerResource, options PostIndexerOperationOptions) (result PostIndexerOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusCreated,
		},
		HttpMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          "/api/v3/indexer",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model IndexerResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
