// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PutIndexerBulkOperationResponse is the result of PutIndexerBulk.
type PutIndexerBulkOperationResponse struct {
	HttpResponse *http.Response
	Model        *IndexerResource
}

// PutIndexerBulk calls PUT /api/v3/indexer/bulk.
func (c Client) PutIndexerBulk(ctx context.Context, input IndexerBulkResource) (result PutIndexerBulkOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusAccepted,
		},
		HttpMethod: http.MethodPut,
		Path:       "/api/v3/indexer/bulk",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model IndexerResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
