// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// IndexerConfigResource is the "IndexerConfigResource" schema.
type IndexerConfigResource struct {
	Id              int `json:"id"`
	MaximumSize     int `json:"maximumSize"`
	MinimumAge      int `json:"minimumAge"`
	Retention       int `json:"retention"`
	RssSyncInterval int `json:"rssSyncInterval"`
}
