// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// IndexerConfigResource is the "IndexerConfigResource" schema.
type IndexerConfigResource struct {
	Id              int `json:"id,omitempty"`
	MaximumSize     int `json:"maximumSize,omitempty"`
	MinimumAge      int `json:"minimumAge,omitempty"`
	Retention       int `json:"retention,omitempty"`
	RssSyncInterval int `json:"rssSyncInterval,omitempty"`
}
