// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PostIndexerActionByNameOperationResponse is the result of PostIndexerActionByName.
type PostIndexerActionByNameOperationResponse struct {
	HttpResponse *http.Response
}

// PostIndexerActionByName calls POST /api/v3/indexer/action/{name}.
func (c Client) PostIndexerActionByName(ctx context.Context, name string, input IndexerResource) (result PostIndexerActionByNameOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodPost,
		Path:       fmt.Sprintf("/api/v3/indexer/action/%s", url.PathEscape(name)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
