// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PostIndexerTestAllOperationResponse is the result of PostIndexerTestAll.
type PostIndexerTestAllOperationResponse struct {
	HttpResponse *http.Response
	Model        []ProviderTestAllResult
}

// PostIndexerTestAll calls POST /api/v3/indexer/testall.
func (c Client) PostIndexerTestAll(ctx context.Context) (result PostIndexerTestAllOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusBadRequest,
		},
		HttpMethod: http.MethodPost,
		Path:       "/api/v3/indexer/testall",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
