// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// LanguageResource is the "LanguageResource" schema.
type LanguageResource struct {
	Id        int    `json:"id,omitempty"`
	Name      string `json:"name,omitempty"`
	NameLower string `json:"nameLower,omitempty"`
}
