// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetLanguageProfileByIdOperationResponse is the result of GetLanguageProfileById.
type GetLanguageProfileByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *LanguageProfileResource
}

// GetLanguageProfileById calls GET /api/v3/languageprofile/{id}.
func (c Client) GetLanguageProfileById(ctx context.Context, id int) (result GetLanguageProfileByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/api/v3/languageprofile/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model LanguageProfileResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
