// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetLanguageProfileOperationResponse is the result of GetLanguageProfile.
type GetLanguageProfileOperationResponse struct {
	HttpResponse *http.Response
	Model        []LanguageProfileResource
}

// GetLanguageProfile calls GET /api/v3/languageprofile.
//
// Deprecated: the document marks this operation deprecated.
func (c Client) GetLanguageProfile(ctx context.Context) (result GetLanguageProfileOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/languageprofile",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
