// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PutLanguageProfileByIdOperationResponse is the result of PutLanguageProfileById.
type PutLanguageProfileByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *LanguageProfileResource
}

// PutLanguageProfileById calls PUT /api/v3/languageprofile/{id}.
//
// Deprecated: the document marks this operation deprecated.
func (c Client) PutLanguageProfileById(ctx context.Context, id string, input LanguageProfileResource) (result PutLanguageProfileByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusAccepted,
		},
		HttpMethod: http.MethodPut,
		Path:       fmt.Sprintf("/api/v3/languageprofile/%s", url.PathEscape(id)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model LanguageProfileResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
