// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PostLanguageProfileOperationResponse is the result of PostLanguageProfile.
type PostLanguageProfileOperationResponse struct {
	HttpResponse *http.Response
	Model        *LanguageProfileResource
}

// PostLanguageProfile calls POST /api/v3/languageprofile.
//
// Deprecated: the document marks this operation deprecated.
func (c Client) PostLanguageProfile(ctx context.Context, input LanguageProfileResource) (result PostLanguageProfileOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusAccepted,
		},
		HttpMethod: http.MethodPost,
		Path:       "/api/v3/languageprofile",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model LanguageProfileResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
