// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetLanguageProfileSchemaOperationResponse is the result of GetLanguageProfileSchema.
type GetLanguageProfileSchemaOperationResponse struct {
	HttpResponse *http.Response
	Model        *LanguageProfileResource
}

// GetLanguageProfileSchema calls GET /api/v3/languageprofile/schema.
//
// Deprecated: the document marks this operation deprecated.
func (c Client) GetLanguageProfileSchema(ctx context.Context) (result GetLanguageProfileSchemaOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/languageprofile/schema",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model LanguageProfileResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
