// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// DeleteLanguageProfileByIdOperationResponse is the result of DeleteLanguageProfileById.
type DeleteLanguageProfileByIdOperationResponse struct {
	HttpResponse *http.Response
}

// DeleteLanguageProfileById calls DELETE /api/v3/languageprofile/{id}.
//
// Deprecated: the document marks this operation deprecated.
func (c Client) DeleteLanguageProfileById(ctx context.Context, id int) (result DeleteLanguageProfileByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodDelete,
		Path:       fmt.Sprintf("/api/v3/languageprofile/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
