// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetLocalizationLanguageOperationResponse is the result of GetLocalizationLanguage.
type GetLocalizationLanguageOperationResponse struct {
	HttpResponse *http.Response
	Model        *LocalizationLanguageResource
}

// GetLocalizationLanguage calls GET /api/v3/localization/language.
func (c Client) GetLocalizationLanguage(ctx context.Context) (result GetLocalizationLanguageOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/localization/language",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model LocalizationLanguageResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
