// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// LocalizationLanguageResource is the "LocalizationLanguageResource" schema.
type LocalizationLanguageResource struct {
	Identifier string `json:"identifier,omitempty"`
}
