// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// LocalizationResource is the "LocalizationResource" schema.
type LocalizationResource struct {
	Id      int               `json:"id,omitempty"`
	Strings map[string]string `json:"strings,omitzero"`
}
