// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// LogResource is the "LogResource" schema.
type LogResource struct {
	Exception     string `json:"exception,omitempty"`
	ExceptionType string `json:"exceptionType,omitempty"`
	Id            int    `json:"id,omitempty"`
	Level         string `json:"level,omitempty"`
	Logger        string `json:"logger,omitempty"`
	Message       string `json:"message,omitempty"`
	Method        string `json:"method,omitempty"`
	Time          string `json:"time,omitempty"`
}
