// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// LogResourcePagingResource is the "LogResourcePagingResource" schema.
type LogResourcePagingResource struct {
	Page          int           `json:"page,omitempty"`
	PageSize      int           `json:"pageSize,omitempty"`
	Records       []LogResource `json:"records,omitzero"`
	SortDirection SortDirection `json:"sortDirection,omitempty"`
	SortKey       string        `json:"sortKey,omitempty"`
	TotalRecords  int           `json:"totalRecords,omitempty"`
}
