// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// RejectionType is the "RejectionType" enum.
type RejectionType string

// Values of RejectionType.
const (
	RejectionTypePermanent RejectionType = "permanent"
	RejectionTypeTemporary RejectionType = "temporary"
)

// PossibleValuesForRejectionType returns every value of RejectionType.
func PossibleValuesForRejectionType() []string {
	return []string{
		string(RejectionTypePermanent),
		string(RejectionTypeTemporary),
	}
}
