// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// ManualImportReprocessResource is the "ManualImportReprocessResource" schema.
type ManualImportReprocessResource struct {
	CustomFormatScore int                       `json:"customFormatScore,omitempty"`
	CustomFormats     []CustomFormatResource    `json:"customFormats,omitzero"`
	DownloadId        string                    `json:"downloadId,omitempty"`
	EpisodeIds        []int                     `json:"episodeIds,omitzero"`
	Episodes          []EpisodeResource         `json:"episodes,omitzero"`
	Id                int                       `json:"id,omitempty"`
	IndexerFlags      int                       `json:"indexerFlags,omitempty"`
	Languages         []Language                `json:"languages,omitzero"`
	Path              string                    `json:"path,omitempty"`
	Quality           *QualityModel             `json:"quality,omitempty"`
	Rejections        []ImportRejectionResource `json:"rejections,omitzero"`
	ReleaseGroup      string                    `json:"releaseGroup,omitempty"`
	ReleaseType       ReleaseType               `json:"releaseType,omitempty"`
	SeasonNumber      int                       `json:"seasonNumber,omitempty"`
	SeriesId          int                       `json:"seriesId,omitempty"`
}
