// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// ImportRejectionResource is the "ImportRejectionResource" schema.
type ImportRejectionResource struct {
	Reason string        `json:"reason,omitempty"`
	Type   RejectionType `json:"type,omitempty"`
}
