// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// ManualImportResource is the "ManualImportResource" schema.
type ManualImportResource struct {
	CustomFormatScore int                       `json:"customFormatScore,omitempty"`
	CustomFormats     []CustomFormatResource    `json:"customFormats,omitzero"`
	DownloadId        string                    `json:"downloadId,omitempty"`
	EpisodeFileId     int                       `json:"episodeFileId,omitempty"`
	Episodes          []EpisodeResource         `json:"episodes,omitzero"`
	FolderName        string                    `json:"folderName,omitempty"`
	Id                int                       `json:"id,omitempty"`
	IndexerFlags      int                       `json:"indexerFlags,omitempty"`
	Languages         []Language                `json:"languages,omitzero"`
	Name              string                    `json:"name,omitempty"`
	Path              string                    `json:"path,omitempty"`
	Quality           *QualityModel             `json:"quality,omitempty"`
	QualityWeight     int                       `json:"qualityWeight,omitempty"`
	Rejections        []ImportRejectionResource `json:"rejections,omitzero"`
	RelativePath      string                    `json:"relativePath,omitempty"`
	ReleaseGroup      string                    `json:"releaseGroup,omitempty"`
	ReleaseType       ReleaseType               `json:"releaseType,omitempty"`
	SeasonNumber      int                       `json:"seasonNumber,omitempty"`
	Series            *SeriesResource           `json:"series,omitempty"`
	Size              int64                     `json:"size,omitempty"`
}
