// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetManualImportOperationResponse is the result of GetManualImport.
type GetManualImportOperationResponse struct {
	HttpResponse *http.Response
	Model        []ManualImportResource
}

// GetManualImportOperationOptions holds the query and header parameters of GetManualImport.
type GetManualImportOperationOptions struct {
	Folder              string
	DownloadId          string
	SeriesId            int
	SeasonNumber        int
	FilterExistingFiles *bool
}

// ToHeaders returns the header parameters the options set.
func (o GetManualImportOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetManualImportOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Folder != "" {
		out.Append("folder", o.Folder)
	}
	if o.DownloadId != "" {
		out.Append("downloadId", o.DownloadId)
	}
	if o.SeriesId != 0 {
		out.Append("seriesId", strconv.Itoa(o.SeriesId))
	}
	if o.SeasonNumber != 0 {
		out.Append("seasonNumber", strconv.Itoa(o.SeasonNumber))
	}
	if o.FilterExistingFiles != nil {
		out.Append("filterExistingFiles", strconv.FormatBool(*o.FilterExistingFiles))
	}
	return &out
}

// GetManualImport calls GET /api/v3/manualimport.
func (c Client) GetManualImport(ctx context.Context, options GetManualImportOperationOptions) (result GetManualImportOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/manualimport",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
