// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetConfigMediaManagementByIdOperationResponse is the result of GetConfigMediaManagementById.
type GetConfigMediaManagementByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *MediaManagementConfigResource
}

// GetConfigMediaManagementById calls GET /api/v3/config/mediamanagement/{id}.
func (c Client) GetConfigMediaManagementById(ctx context.Context, id int) (result GetConfigMediaManagementByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/api/v3/config/mediamanagement/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model MediaManagementConfigResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
