// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetMediaCoverBySeriesIdByFilenameOperationResponse is the result of GetMediaCoverBySeriesIdByFilename.
//
// The operation answers image/*, left unread in HttpResponse.Body, which
// the caller must close.
type GetMediaCoverBySeriesIdByFilenameOperationResponse struct {
	HttpResponse *http.Response
}

// GetMediaCoverBySeriesIdByFilename calls GET /api/v3/mediacover/{seriesId}/{filename}.
func (c Client) GetMediaCoverBySeriesIdByFilename(ctx context.Context, seriesId int, filename string) (result GetMediaCoverBySeriesIdByFilenameOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:     http.MethodGet,
		Path:           fmt.Sprintf("/api/v3/mediacover/%d/%s", seriesId, url.PathEscape(filename)),
		StreamResponse: true,
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
