// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// EpisodeTitleRequiredType is the "EpisodeTitleRequiredType" enum.
type EpisodeTitleRequiredType string

// Values of EpisodeTitleRequiredType.
const (
	EpisodeTitleRequiredTypeAlways             EpisodeTitleRequiredType = "always"
	EpisodeTitleRequiredTypeBulkSeasonReleases EpisodeTitleRequiredType = "bulkSeasonReleases"
	EpisodeTitleRequiredTypeNever              EpisodeTitleRequiredType = "never"
)

// PossibleValuesForEpisodeTitleRequiredType returns every value of EpisodeTitleRequiredType.
func PossibleValuesForEpisodeTitleRequiredType() []string {
	return []string{
		string(EpisodeTitleRequiredTypeAlways),
		string(EpisodeTitleRequiredTypeBulkSeasonReleases),
		string(EpisodeTitleRequiredTypeNever),
	}
}

// FileDateType is the "FileDateType" enum.
type FileDateType string

// Values of FileDateType.
const (
	FileDateTypeNone         FileDateType = "none"
	FileDateTypeLocalAirDate FileDateType = "localAirDate"
	FileDateTypeUtcAirDate   FileDateType = "utcAirDate"
)

// PossibleValuesForFileDateType returns every value of FileDateType.
func PossibleValuesForFileDateType() []string {
	return []string{
		string(FileDateTypeNone),
		string(FileDateTypeLocalAirDate),
		string(FileDateTypeUtcAirDate),
	}
}

// ProperDownloadTypes is the "ProperDownloadTypes" enum.
type ProperDownloadTypes string

// Values of ProperDownloadTypes.
const (
	ProperDownloadTypesPreferAndUpgrade ProperDownloadTypes = "preferAndUpgrade"
	ProperDownloadTypesDoNotUpgrade     ProperDownloadTypes = "doNotUpgrade"
	ProperDownloadTypesDoNotPrefer      ProperDownloadTypes = "doNotPrefer"
)

// PossibleValuesForProperDownloadTypes returns every value of ProperDownloadTypes.
func PossibleValuesForProperDownloadTypes() []string {
	return []string{
		string(ProperDownloadTypesPreferAndUpgrade),
		string(ProperDownloadTypesDoNotUpgrade),
		string(ProperDownloadTypesDoNotPrefer),
	}
}

// RescanAfterRefreshType is the "RescanAfterRefreshType" enum.
type RescanAfterRefreshType string

// Values of RescanAfterRefreshType.
const (
	RescanAfterRefreshTypeAlways      RescanAfterRefreshType = "always"
	RescanAfterRefreshTypeAfterManual RescanAfterRefreshType = "afterManual"
	RescanAfterRefreshTypeNever       RescanAfterRefreshType = "never"
)

// PossibleValuesForRescanAfterRefreshType returns every value of RescanAfterRefreshType.
func PossibleValuesForRescanAfterRefreshType() []string {
	return []string{
		string(RescanAfterRefreshTypeAlways),
		string(RescanAfterRefreshTypeAfterManual),
		string(RescanAfterRefreshTypeNever),
	}
}
