// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// MetadataResource is the "MetadataResource" schema.
type MetadataResource struct {
	ConfigContract     string             `json:"configContract,omitempty"`
	Enable             *bool              `json:"enable,omitempty"`
	Fields             []Field            `json:"fields,omitzero"`
	Id                 int                `json:"id,omitempty"`
	Implementation     string             `json:"implementation,omitempty"`
	ImplementationName string             `json:"implementationName,omitempty"`
	InfoLink           string             `json:"infoLink,omitempty"`
	Message            *ProviderMessage   `json:"message,omitempty"`
	Name               string             `json:"name,omitempty"`
	Presets            []MetadataResource `json:"presets,omitzero"`
	Tags               []int              `json:"tags,omitzero"`
}
