// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PostMetadataTestOperationResponse is the result of PostMetadataTest.
type PostMetadataTestOperationResponse struct {
	HttpResponse *http.Response
}

// PostMetadataTestOperationOptions holds the query and header parameters of PostMetadataTest.
type PostMetadataTestOperationOptions struct {
	ForceTest *bool
}

// ToHeaders returns the header parameters the options set.
func (o PostMetadataTestOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PostMetadataTestOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.ForceTest != nil {
		out.Append("forceTest", strconv.FormatBool(*o.ForceTest))
	}
	return &out
}

// PostMetadataTest calls POST /api/v3/metadata/test.
func (c Client) PostMetadataTest(ctx context.Context, input MetadataResource, options PostMetadataTestOperationOptions) (result PostMetadataTestOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          "/api/v3/metadata/test",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
