// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PostMetadataOperationResponse is the result of PostMetadata.
type PostMetadataOperationResponse struct {
	HttpResponse *http.Response
	Model        *MetadataResource
}

// PostMetadataOperationOptions holds the query and header parameters of PostMetadata.
type PostMetadataOperationOptions struct {
	ForceSave *bool
}

// ToHeaders returns the header parameters the options set.
func (o PostMetadataOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PostMetadataOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.ForceSave != nil {
		out.Append("forceSave", strconv.FormatBool(*o.ForceSave))
	}
	return &out
}

// PostMetadata calls POST /api/v3/metadata.
func (c Client) PostMetadata(ctx context.Context, input MetadataResource, options PostMetadataOperationOptions) (result PostMetadataOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusCreated,
		},
		HttpMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          "/api/v3/metadata",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model MetadataResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
