// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// DeleteMetadataByIdOperationResponse is the result of DeleteMetadataById.
type DeleteMetadataByIdOperationResponse struct {
	HttpResponse *http.Response
}

// DeleteMetadataById calls DELETE /api/v3/metadata/{id}.
func (c Client) DeleteMetadataById(ctx context.Context, id int) (result DeleteMetadataByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodDelete,
		Path:       fmt.Sprintf("/api/v3/metadata/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
