// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetConfigNamingByIdOperationResponse is the result of GetConfigNamingById.
type GetConfigNamingByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *NamingConfigResource
}

// GetConfigNamingById calls GET /api/v3/config/naming/{id}.
func (c Client) GetConfigNamingById(ctx context.Context, id int) (result GetConfigNamingByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/api/v3/config/naming/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model NamingConfigResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
