// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"net/http"
	"testing"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

func TestOperationGetConfigNamingExamples(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 200, "application/json", "{}")
	result, err := c.GetConfigNamingExamples(t.Context(), GetConfigNamingExamplesOperationOptions{
		RenameEpisodes:               new(true),
		ReplaceIllegalCharacters:     new(true),
		ColonReplacementFormat:       7,
		CustomColonReplacementFormat: "v-CustomColonReplacementFormat",
		MultiEpisodeStyle:            7,
		StandardEpisodeFormat:        "v-StandardEpisodeFormat",
		DailyEpisodeFormat:           "v-DailyEpisodeFormat",
		AnimeEpisodeFormat:           "v-AnimeEpisodeFormat",
		SeriesFolderFormat:           "v-SeriesFolderFormat",
		SeasonFolderFormat:           "v-SeasonFolderFormat",
		SpecialsFolderFormat:         "v-SpecialsFolderFormat",
		Id:                           7,
		ResourceName:                 "v-ResourceName",
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodGet, "/api/v3/config/naming/examples")
	expectQuery(t, r, "renameEpisodes", "true")
	expectQuery(t, r, "replaceIllegalCharacters", "true")
	expectQuery(t, r, "colonReplacementFormat", "7")
	expectQuery(t, r, "customColonReplacementFormat", "v-CustomColonReplacementFormat")
	expectQuery(t, r, "multiEpisodeStyle", "7")
	expectQuery(t, r, "standardEpisodeFormat", "v-StandardEpisodeFormat")
	expectQuery(t, r, "dailyEpisodeFormat", "v-DailyEpisodeFormat")
	expectQuery(t, r, "animeEpisodeFormat", "v-AnimeEpisodeFormat")
	expectQuery(t, r, "seriesFolderFormat", "v-SeriesFolderFormat")
	expectQuery(t, r, "seasonFolderFormat", "v-SeasonFolderFormat")
	expectQuery(t, r, "specialsFolderFormat", "v-SpecialsFolderFormat")
	expectQuery(t, r, "id", "7")
	expectQuery(t, r, "resourceName", "v-ResourceName")
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 200 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}
	if result.Model == nil {
		t.Error("the model was not decoded")
	}

	// an answer that does not decode is an error, with the response
	c, _ = newOperationServer(t, 200, "application/json", "<html>")
	result, err = c.GetConfigNamingExamples(t.Context(), GetConfigNamingExamplesOperationOptions{
		RenameEpisodes:               new(true),
		ReplaceIllegalCharacters:     new(true),
		ColonReplacementFormat:       7,
		CustomColonReplacementFormat: "v-CustomColonReplacementFormat",
		MultiEpisodeStyle:            7,
		StandardEpisodeFormat:        "v-StandardEpisodeFormat",
		DailyEpisodeFormat:           "v-DailyEpisodeFormat",
		AnimeEpisodeFormat:           "v-AnimeEpisodeFormat",
		SeriesFolderFormat:           "v-SeriesFolderFormat",
		SeasonFolderFormat:           "v-SeasonFolderFormat",
		SpecialsFolderFormat:         "v-SpecialsFolderFormat",
		Id:                           7,
		ResourceName:                 "v-ResourceName",
	})
	if err == nil || client.StatusCode(err) != 0 || result.HttpResponse == nil {
		t.Errorf("an answer that does not decode = %v", err)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.GetConfigNamingExamples(t.Context(), GetConfigNamingExamplesOperationOptions{
		RenameEpisodes:               new(true),
		ReplaceIllegalCharacters:     new(true),
		ColonReplacementFormat:       7,
		CustomColonReplacementFormat: "v-CustomColonReplacementFormat",
		MultiEpisodeStyle:            7,
		StandardEpisodeFormat:        "v-StandardEpisodeFormat",
		DailyEpisodeFormat:           "v-DailyEpisodeFormat",
		AnimeEpisodeFormat:           "v-AnimeEpisodeFormat",
		SeriesFolderFormat:           "v-SeriesFolderFormat",
		SeasonFolderFormat:           "v-SeasonFolderFormat",
		SpecialsFolderFormat:         "v-SpecialsFolderFormat",
		Id:                           7,
		ResourceName:                 "v-ResourceName",
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
