// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// NamingConfigResource is the "NamingConfigResource" schema.
type NamingConfigResource struct {
	AnimeEpisodeFormat           string `json:"animeEpisodeFormat"`
	ColonReplacementFormat       int    `json:"colonReplacementFormat"`
	CustomColonReplacementFormat string `json:"customColonReplacementFormat"`
	DailyEpisodeFormat           string `json:"dailyEpisodeFormat"`
	Id                           int    `json:"id"`
	MultiEpisodeStyle            int    `json:"multiEpisodeStyle"`
	RenameEpisodes               *bool  `json:"renameEpisodes,omitempty"`
	ReplaceIllegalCharacters     *bool  `json:"replaceIllegalCharacters,omitempty"`
	SeasonFolderFormat           string `json:"seasonFolderFormat"`
	SeriesFolderFormat           string `json:"seriesFolderFormat"`
	SpecialsFolderFormat         string `json:"specialsFolderFormat"`
	StandardEpisodeFormat        string `json:"standardEpisodeFormat"`
}
