// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"encoding/json"
	"net/http"
	"strconv"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetConfigNamingExamplesOperationResponse is the result of GetConfigNamingExamples.
type GetConfigNamingExamplesOperationResponse struct {
	HttpResponse *http.Response
	Model        json.RawMessage
}

// GetConfigNamingExamplesOperationOptions holds the query and header parameters of GetConfigNamingExamples.
type GetConfigNamingExamplesOperationOptions struct {
	RenameEpisodes               *bool
	ReplaceIllegalCharacters     *bool
	ColonReplacementFormat       int
	CustomColonReplacementFormat string
	MultiEpisodeStyle            int
	StandardEpisodeFormat        string
	DailyEpisodeFormat           string
	AnimeEpisodeFormat           string
	SeriesFolderFormat           string
	SeasonFolderFormat           string
	SpecialsFolderFormat         string
	Id                           int
	ResourceName                 string
}

// ToHeaders returns the header parameters the options set.
func (o GetConfigNamingExamplesOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetConfigNamingExamplesOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.RenameEpisodes != nil {
		out.Append("renameEpisodes", strconv.FormatBool(*o.RenameEpisodes))
	}
	if o.ReplaceIllegalCharacters != nil {
		out.Append("replaceIllegalCharacters", strconv.FormatBool(*o.ReplaceIllegalCharacters))
	}
	if o.ColonReplacementFormat != 0 {
		out.Append("colonReplacementFormat", strconv.Itoa(o.ColonReplacementFormat))
	}
	if o.CustomColonReplacementFormat != "" {
		out.Append("customColonReplacementFormat", o.CustomColonReplacementFormat)
	}
	if o.MultiEpisodeStyle != 0 {
		out.Append("multiEpisodeStyle", strconv.Itoa(o.MultiEpisodeStyle))
	}
	if o.StandardEpisodeFormat != "" {
		out.Append("standardEpisodeFormat", o.StandardEpisodeFormat)
	}
	if o.DailyEpisodeFormat != "" {
		out.Append("dailyEpisodeFormat", o.DailyEpisodeFormat)
	}
	if o.AnimeEpisodeFormat != "" {
		out.Append("animeEpisodeFormat", o.AnimeEpisodeFormat)
	}
	if o.SeriesFolderFormat != "" {
		out.Append("seriesFolderFormat", o.SeriesFolderFormat)
	}
	if o.SeasonFolderFormat != "" {
		out.Append("seasonFolderFormat", o.SeasonFolderFormat)
	}
	if o.SpecialsFolderFormat != "" {
		out.Append("specialsFolderFormat", o.SpecialsFolderFormat)
	}
	if o.Id != 0 {
		out.Append("id", strconv.Itoa(o.Id))
	}
	if o.ResourceName != "" {
		out.Append("resourceName", o.ResourceName)
	}
	return &out
}

// GetConfigNamingExamples calls GET /api/v3/config/naming/examples.
func (c Client) GetConfigNamingExamples(ctx context.Context, options GetConfigNamingExamplesOperationOptions) (result GetConfigNamingExamplesOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/config/naming/examples",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
