// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// NamingConfigResource is the "NamingConfigResource" schema.
type NamingConfigResource struct {
	AnimeEpisodeFormat           string `json:"animeEpisodeFormat,omitempty"`
	ColonReplacementFormat       int    `json:"colonReplacementFormat,omitempty"`
	CustomColonReplacementFormat string `json:"customColonReplacementFormat,omitempty"`
	DailyEpisodeFormat           string `json:"dailyEpisodeFormat,omitempty"`
	Id                           int    `json:"id,omitempty"`
	MultiEpisodeStyle            int    `json:"multiEpisodeStyle,omitempty"`
	RenameEpisodes               *bool  `json:"renameEpisodes,omitempty"`
	ReplaceIllegalCharacters     *bool  `json:"replaceIllegalCharacters,omitempty"`
	SeasonFolderFormat           string `json:"seasonFolderFormat,omitempty"`
	SeriesFolderFormat           string `json:"seriesFolderFormat,omitempty"`
	SpecialsFolderFormat         string `json:"specialsFolderFormat,omitempty"`
	StandardEpisodeFormat        string `json:"standardEpisodeFormat,omitempty"`
}
