// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// NotificationResource is the "NotificationResource" schema.
type NotificationResource struct {
	ConfigContract                        string                 `json:"configContract,omitempty"`
	Fields                                []Field                `json:"fields,omitzero"`
	Id                                    int                    `json:"id,omitempty"`
	Implementation                        string                 `json:"implementation,omitempty"`
	ImplementationName                    string                 `json:"implementationName,omitempty"`
	IncludeHealthWarnings                 *bool                  `json:"includeHealthWarnings,omitempty"`
	InfoLink                              string                 `json:"infoLink,omitempty"`
	Link                                  string                 `json:"link,omitempty"`
	Message                               *ProviderMessage       `json:"message,omitempty"`
	Name                                  string                 `json:"name,omitempty"`
	OnApplicationUpdate                   *bool                  `json:"onApplicationUpdate,omitempty"`
	OnDownload                            *bool                  `json:"onDownload,omitempty"`
	OnEpisodeFileDelete                   *bool                  `json:"onEpisodeFileDelete,omitempty"`
	OnEpisodeFileDeleteForUpgrade         *bool                  `json:"onEpisodeFileDeleteForUpgrade,omitempty"`
	OnGrab                                *bool                  `json:"onGrab,omitempty"`
	OnHealthIssue                         *bool                  `json:"onHealthIssue,omitempty"`
	OnHealthRestored                      *bool                  `json:"onHealthRestored,omitempty"`
	OnImportComplete                      *bool                  `json:"onImportComplete,omitempty"`
	OnManualInteractionRequired           *bool                  `json:"onManualInteractionRequired,omitempty"`
	OnRename                              *bool                  `json:"onRename,omitempty"`
	OnSeriesAdd                           *bool                  `json:"onSeriesAdd,omitempty"`
	OnSeriesDelete                        *bool                  `json:"onSeriesDelete,omitempty"`
	OnUpgrade                             *bool                  `json:"onUpgrade,omitempty"`
	Presets                               []NotificationResource `json:"presets,omitzero"`
	SupportsOnApplicationUpdate           *bool                  `json:"supportsOnApplicationUpdate,omitempty"`
	SupportsOnDownload                    *bool                  `json:"supportsOnDownload,omitempty"`
	SupportsOnEpisodeFileDelete           *bool                  `json:"supportsOnEpisodeFileDelete,omitempty"`
	SupportsOnEpisodeFileDeleteForUpgrade *bool                  `json:"supportsOnEpisodeFileDeleteForUpgrade,omitempty"`
	SupportsOnGrab                        *bool                  `json:"supportsOnGrab,omitempty"`
	SupportsOnHealthIssue                 *bool                  `json:"supportsOnHealthIssue,omitempty"`
	SupportsOnHealthRestored              *bool                  `json:"supportsOnHealthRestored,omitempty"`
	SupportsOnImportComplete              *bool                  `json:"supportsOnImportComplete,omitempty"`
	SupportsOnManualInteractionRequired   *bool                  `json:"supportsOnManualInteractionRequired,omitempty"`
	SupportsOnRename                      *bool                  `json:"supportsOnRename,omitempty"`
	SupportsOnSeriesAdd                   *bool                  `json:"supportsOnSeriesAdd,omitempty"`
	SupportsOnSeriesDelete                *bool                  `json:"supportsOnSeriesDelete,omitempty"`
	SupportsOnUpgrade                     *bool                  `json:"supportsOnUpgrade,omitempty"`
	Tags                                  []int                  `json:"tags,omitzero"`
	TestCommand                           string                 `json:"testCommand,omitempty"`
}
