// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// ParseResource is the "ParseResource" schema.
type ParseResource struct {
	CustomFormatScore int                    `json:"customFormatScore,omitempty"`
	CustomFormats     []CustomFormatResource `json:"customFormats,omitzero"`
	Episodes          []EpisodeResource      `json:"episodes,omitzero"`
	Id                int                    `json:"id,omitempty"`
	Languages         []Language             `json:"languages,omitzero"`
	ParsedEpisodeInfo *ParsedEpisodeInfo     `json:"parsedEpisodeInfo,omitempty"`
	Series            *SeriesResource        `json:"series,omitempty"`
	Title             string                 `json:"title,omitempty"`
}
