// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// SeriesTitleInfo is the "SeriesTitleInfo" schema.
type SeriesTitleInfo struct {
	AllTitles        []string `json:"allTitles,omitzero"`
	Title            string   `json:"title,omitempty"`
	TitleWithoutYear string   `json:"titleWithoutYear,omitempty"`
	Year             int      `json:"year,omitempty"`
}
