// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// ParsedEpisodeInfo is the "ParsedEpisodeInfo" schema.
type ParsedEpisodeInfo struct {
	AbsoluteEpisodeNumbers        []int            `json:"absoluteEpisodeNumbers,omitzero"`
	AirDate                       string           `json:"airDate,omitempty"`
	DailyPart                     int              `json:"dailyPart,omitempty"`
	EpisodeNumbers                []int            `json:"episodeNumbers,omitzero"`
	FullSeason                    *bool            `json:"fullSeason,omitempty"`
	IsAbsoluteNumbering           *bool            `json:"isAbsoluteNumbering,omitempty"`
	IsDaily                       *bool            `json:"isDaily,omitempty"`
	IsMiniSeries                  *bool            `json:"isMiniSeries,omitempty"`
	IsMultiSeason                 *bool            `json:"isMultiSeason,omitempty"`
	IsPartialSeason               *bool            `json:"isPartialSeason,omitempty"`
	IsPossibleSceneSeasonSpecial  *bool            `json:"isPossibleSceneSeasonSpecial,omitempty"`
	IsPossibleSpecialEpisode      *bool            `json:"isPossibleSpecialEpisode,omitempty"`
	IsSeasonExtra                 *bool            `json:"isSeasonExtra,omitempty"`
	IsSplitEpisode                *bool            `json:"isSplitEpisode,omitempty"`
	Languages                     []Language       `json:"languages,omitzero"`
	Quality                       *QualityModel    `json:"quality,omitempty"`
	ReleaseGroup                  string           `json:"releaseGroup,omitempty"`
	ReleaseHash                   string           `json:"releaseHash,omitempty"`
	ReleaseTitle                  string           `json:"releaseTitle,omitempty"`
	ReleaseTokens                 string           `json:"releaseTokens,omitempty"`
	ReleaseType                   ReleaseType      `json:"releaseType,omitempty"`
	SeasonNumber                  int              `json:"seasonNumber,omitempty"`
	SeasonPart                    int              `json:"seasonPart,omitempty"`
	SeriesTitle                   string           `json:"seriesTitle,omitempty"`
	SeriesTitleInfo               *SeriesTitleInfo `json:"seriesTitleInfo,omitempty"`
	Special                       *bool            `json:"special,omitempty"`
	SpecialAbsoluteEpisodeNumbers []float64        `json:"specialAbsoluteEpisodeNumbers,omitzero"`
}
