// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetParseOperationResponse is the result of GetParse.
type GetParseOperationResponse struct {
	HttpResponse *http.Response
	Model        *ParseResource
}

// GetParseOperationOptions holds the query and header parameters of GetParse.
type GetParseOperationOptions struct {
	Title string
	Path  string
}

// ToHeaders returns the header parameters the options set.
func (o GetParseOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetParseOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Title != "" {
		out.Append("title", o.Title)
	}
	if o.Path != "" {
		out.Append("path", o.Path)
	}
	return &out
}

// GetParse calls GET /api/v3/parse.
func (c Client) GetParse(ctx context.Context, options GetParseOperationOptions) (result GetParseOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/parse",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model ParseResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
