// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PostQualityProfileOperationResponse is the result of PostQualityProfile.
type PostQualityProfileOperationResponse struct {
	HttpResponse *http.Response
	Model        *QualityProfileResource
}

// PostQualityProfile calls POST /api/v3/qualityprofile.
func (c Client) PostQualityProfile(ctx context.Context, input QualityProfileResource) (result PostQualityProfileOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusCreated,
		},
		HttpMethod: http.MethodPost,
		Path:       "/api/v3/qualityprofile",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model QualityProfileResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
