// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PutQualityDefinitionUpdateOperationResponse is the result of PutQualityDefinitionUpdate.
type PutQualityDefinitionUpdateOperationResponse struct {
	HttpResponse *http.Response
	Model        []QualityDefinitionResource
}

// PutQualityDefinitionUpdate calls PUT /api/v3/qualitydefinition/update.
func (c Client) PutQualityDefinitionUpdate(ctx context.Context, input []QualityDefinitionResource) (result PutQualityDefinitionUpdateOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusAccepted,
		},
		HttpMethod: http.MethodPut,
		Path:       "/api/v3/qualitydefinition/update",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
