// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetQualityDefinitionLimitsOperationResponse is the result of GetQualityDefinitionLimits.
type GetQualityDefinitionLimitsOperationResponse struct {
	HttpResponse *http.Response
	Model        *QualityDefinitionLimitsResource
}

// GetQualityDefinitionLimits calls GET /api/v3/qualitydefinition/limits.
func (c Client) GetQualityDefinitionLimits(ctx context.Context) (result GetQualityDefinitionLimitsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/qualitydefinition/limits",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model QualityDefinitionLimitsResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
