// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetQualityDefinitionByIdOperationResponse is the result of GetQualityDefinitionById.
type GetQualityDefinitionByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *QualityDefinitionResource
}

// GetQualityDefinitionById calls GET /api/v3/qualitydefinition/{id}.
func (c Client) GetQualityDefinitionById(ctx context.Context, id int) (result GetQualityDefinitionByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/api/v3/qualitydefinition/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model QualityDefinitionResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
