// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetQualityProfileSchemaOperationResponse is the result of GetQualityProfileSchema.
type GetQualityProfileSchemaOperationResponse struct {
	HttpResponse *http.Response
	Model        *QualityProfileResource
}

// GetQualityProfileSchema calls GET /api/v3/qualityprofile/schema.
func (c Client) GetQualityProfileSchema(ctx context.Context) (result GetQualityProfileSchemaOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/qualityprofile/schema",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model QualityProfileResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
