// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// QualityDefinitionLimitsResource is the "QualityDefinitionLimitsResource" schema.
type QualityDefinitionLimitsResource struct {
	Max int `json:"max,omitempty"`
	Min int `json:"min,omitempty"`
}
