// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// DeleteQualityProfileByIdOperationResponse is the result of DeleteQualityProfileById.
type DeleteQualityProfileByIdOperationResponse struct {
	HttpResponse *http.Response
}

// DeleteQualityProfileById calls DELETE /api/v3/qualityprofile/{id}.
func (c Client) DeleteQualityProfileById(ctx context.Context, id int) (result DeleteQualityProfileByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodDelete,
		Path:       fmt.Sprintf("/api/v3/qualityprofile/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
