// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// QualityDefinitionResource is the "QualityDefinitionResource" schema.
type QualityDefinitionResource struct {
	Id            int      `json:"id,omitempty"`
	MaxSize       float64  `json:"maxSize,omitempty"`
	MinSize       float64  `json:"minSize,omitempty"`
	PreferredSize float64  `json:"preferredSize,omitempty"`
	Quality       *Quality `json:"quality,omitempty"`
	Title         string   `json:"title,omitempty"`
	Weight        int      `json:"weight,omitempty"`
}
