// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PutQualityDefinitionByIdOperationResponse is the result of PutQualityDefinitionById.
type PutQualityDefinitionByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *QualityDefinitionResource
}

// PutQualityDefinitionById calls PUT /api/v3/qualitydefinition/{id}.
func (c Client) PutQualityDefinitionById(ctx context.Context, id string, input QualityDefinitionResource) (result PutQualityDefinitionByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusAccepted,
		},
		HttpMethod: http.MethodPut,
		Path:       fmt.Sprintf("/api/v3/qualitydefinition/%s", url.PathEscape(id)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model QualityDefinitionResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
