// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"net/http"
	"slices"
	"testing"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

func TestOperationGetQueue(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 200, "application/json", "{}")
	result, err := c.GetQueue(t.Context(), GetQueueOperationOptions{
		Page:                      7,
		PageSize:                  7,
		SortKey:                   "v-SortKey",
		SortDirection:             SortDirectionDefault,
		IncludeUnknownSeriesItems: new(true),
		IncludeSeries:             new(true),
		IncludeEpisode:            new(true),
		SeriesIds:                 []int{1, 2},
		Protocol:                  DownloadProtocolUnknown,
		Languages:                 []int{1, 2},
		Quality:                   []int{1, 2},
		Status:                    []QueueStatus{QueueStatusUnknown, QueueStatusFallback},
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodGet, "/api/v3/queue")
	expectQuery(t, r, "page", "7")
	expectQuery(t, r, "pageSize", "7")
	expectQuery(t, r, "sortKey", "v-SortKey")
	expectQuery(t, r, "sortDirection", "default")
	expectQuery(t, r, "includeUnknownSeriesItems", "true")
	expectQuery(t, r, "includeSeries", "true")
	expectQuery(t, r, "includeEpisode", "true")
	expectQuery(t, r, "seriesIds", "1", "2")
	expectQuery(t, r, "protocol", "unknown")
	expectQuery(t, r, "languages", "1", "2")
	expectQuery(t, r, "quality", "1", "2")
	expectQuery(t, r, "status", "unknown", "fallback")
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 200 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}
	if result.Model == nil {
		t.Error("the model was not decoded")
	}

	// an answer that does not decode is an error, with the response
	c, _ = newOperationServer(t, 200, "application/json", "<html>")
	result, err = c.GetQueue(t.Context(), GetQueueOperationOptions{
		Page:                      7,
		PageSize:                  7,
		SortKey:                   "v-SortKey",
		SortDirection:             SortDirectionDefault,
		IncludeUnknownSeriesItems: new(true),
		IncludeSeries:             new(true),
		IncludeEpisode:            new(true),
		SeriesIds:                 []int{1, 2},
		Protocol:                  DownloadProtocolUnknown,
		Languages:                 []int{1, 2},
		Quality:                   []int{1, 2},
		Status:                    []QueueStatus{QueueStatusUnknown, QueueStatusFallback},
	})
	if err == nil || client.StatusCode(err) != 0 || result.HttpResponse == nil {
		t.Errorf("an answer that does not decode = %v", err)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.GetQueue(t.Context(), GetQueueOperationOptions{
		Page:                      7,
		PageSize:                  7,
		SortKey:                   "v-SortKey",
		SortDirection:             SortDirectionDefault,
		IncludeUnknownSeriesItems: new(true),
		IncludeSeries:             new(true),
		IncludeEpisode:            new(true),
		SeriesIds:                 []int{1, 2},
		Protocol:                  DownloadProtocolUnknown,
		Languages:                 []int{1, 2},
		Quality:                   []int{1, 2},
		Status:                    []QueueStatus{QueueStatusUnknown, QueueStatusFallback},
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}

func TestOperationGetQueueComplete(t *testing.T) {
	t.Parallel()

	c, pages := pagedServer(t, "page", "{}", 2)
	result, err := c.GetQueueComplete(t.Context(), GetQueueOperationOptions{PageSize: 1})
	if err != nil {
		t.Fatal(err)
	}
	// pages of one from the first, until the second reaches the total
	if len(result.Items) != 2 || !slices.Equal(*pages, []string{"1", "2"}) || result.LatestHttpResponse == nil {
		t.Errorf("Complete = %d items over pages %q", len(result.Items), *pages)
	}
}
