// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// DeleteQueueBulkOperationResponse is the result of DeleteQueueBulk.
type DeleteQueueBulkOperationResponse struct {
	HttpResponse *http.Response
}

// DeleteQueueBulkOperationOptions holds the query and header parameters of DeleteQueueBulk.
type DeleteQueueBulkOperationOptions struct {
	RemoveFromClient *bool
	Blocklist        *bool
	SkipRedownload   *bool
	ChangeCategory   *bool
}

// ToHeaders returns the header parameters the options set.
func (o DeleteQueueBulkOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o DeleteQueueBulkOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.RemoveFromClient != nil {
		out.Append("removeFromClient", strconv.FormatBool(*o.RemoveFromClient))
	}
	if o.Blocklist != nil {
		out.Append("blocklist", strconv.FormatBool(*o.Blocklist))
	}
	if o.SkipRedownload != nil {
		out.Append("skipRedownload", strconv.FormatBool(*o.SkipRedownload))
	}
	if o.ChangeCategory != nil {
		out.Append("changeCategory", strconv.FormatBool(*o.ChangeCategory))
	}
	return &out
}

// DeleteQueueBulk calls DELETE /api/v3/queue/bulk.
func (c Client) DeleteQueueBulk(ctx context.Context, input QueueBulkResource, options DeleteQueueBulkOperationOptions) (result DeleteQueueBulkOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodDelete,
		OptionsObject: options,
		Path:          "/api/v3/queue/bulk",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
