// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// QueueResourcePagingResource is the "QueueResourcePagingResource" schema.
type QueueResourcePagingResource struct {
	Page          int             `json:"page,omitempty"`
	PageSize      int             `json:"pageSize,omitempty"`
	Records       []QueueResource `json:"records,omitzero"`
	SortDirection SortDirection   `json:"sortDirection,omitempty"`
	SortKey       string          `json:"sortKey,omitempty"`
	TotalRecords  int             `json:"totalRecords,omitempty"`
}
