// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// QueueStatusResource is the "QueueStatusResource" schema.
type QueueStatusResource struct {
	Count           int   `json:"count,omitempty"`
	Errors          *bool `json:"errors,omitempty"`
	Id              int   `json:"id,omitempty"`
	TotalCount      int   `json:"totalCount,omitempty"`
	UnknownCount    int   `json:"unknownCount,omitempty"`
	UnknownErrors   *bool `json:"unknownErrors,omitempty"`
	UnknownWarnings *bool `json:"unknownWarnings,omitempty"`
	Warnings        *bool `json:"warnings,omitempty"`
}
