// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetQueueStatusOperationResponse is the result of GetQueueStatus.
type GetQueueStatusOperationResponse struct {
	HttpResponse *http.Response
	Model        *QueueStatusResource
}

// GetQueueStatus calls GET /api/v3/queue/status.
func (c Client) GetQueueStatus(ctx context.Context) (result GetQueueStatusOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/queue/status",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model QueueStatusResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
