// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PostQueueGrabBulkOperationResponse is the result of PostQueueGrabBulk.
type PostQueueGrabBulkOperationResponse struct {
	HttpResponse *http.Response
}

// PostQueueGrabBulk calls POST /api/v3/queue/grab/bulk.
func (c Client) PostQueueGrabBulk(ctx context.Context, input QueueBulkResource) (result PostQueueGrabBulkOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodPost,
		Path:       "/api/v3/queue/grab/bulk",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
