// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PostQueueGrabByIdOperationResponse is the result of PostQueueGrabById.
type PostQueueGrabByIdOperationResponse struct {
	HttpResponse *http.Response
}

// PostQueueGrabById calls POST /api/v3/queue/grab/{id}.
func (c Client) PostQueueGrabById(ctx context.Context, id int) (result PostQueueGrabByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodPost,
		Path:       fmt.Sprintf("/api/v3/queue/grab/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
