// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetQueueOperationResponse is the result of GetQueue.
type GetQueueOperationResponse struct {
	HttpResponse *http.Response
	Model        *QueueResourcePagingResource
}

// GetQueueOperationOptions holds the query and header parameters of GetQueue.
type GetQueueOperationOptions struct {
	Page                      int
	PageSize                  int
	SortKey                   string
	SortDirection             SortDirection
	IncludeUnknownSeriesItems *bool
	IncludeSeries             *bool
	IncludeEpisode            *bool
	SeriesIds                 []int
	Protocol                  DownloadProtocol
	Languages                 []int
	Quality                   []int
	Status                    []QueueStatus
}

// ToHeaders returns the header parameters the options set.
func (o GetQueueOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetQueueOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Page != 0 {
		out.Append("page", strconv.Itoa(o.Page))
	}
	if o.PageSize != 0 {
		out.Append("pageSize", strconv.Itoa(o.PageSize))
	}
	if o.SortKey != "" {
		out.Append("sortKey", o.SortKey)
	}
	if o.SortDirection != "" {
		out.Append("sortDirection", string(o.SortDirection))
	}
	if o.IncludeUnknownSeriesItems != nil {
		out.Append("includeUnknownSeriesItems", strconv.FormatBool(*o.IncludeUnknownSeriesItems))
	}
	if o.IncludeSeries != nil {
		out.Append("includeSeries", strconv.FormatBool(*o.IncludeSeries))
	}
	if o.IncludeEpisode != nil {
		out.Append("includeEpisode", strconv.FormatBool(*o.IncludeEpisode))
	}
	for _, v := range o.SeriesIds {
		out.Append("seriesIds", strconv.Itoa(v))
	}
	if o.Protocol != "" {
		out.Append("protocol", string(o.Protocol))
	}
	for _, v := range o.Languages {
		out.Append("languages", strconv.Itoa(v))
	}
	for _, v := range o.Quality {
		out.Append("quality", strconv.Itoa(v))
	}
	for _, v := range o.Status {
		out.Append("status", string(v))
	}
	return &out
}

// GetQueue calls GET /api/v3/queue.
func (c Client) GetQueue(ctx context.Context, options GetQueueOperationOptions) (result GetQueueOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/queue",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model QueueResourcePagingResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}

// GetQueueCompleteResult is every result GetQueueComplete loaded.
type GetQueueCompleteResult struct {
	LatestHttpResponse *http.Response
	Items              []QueueResource
}

// GetQueueComplete calls GetQueue page by page, from options.Page (the first page
// when unset), until every result is loaded. options.PageSize is the page size,
// client.DefaultPageSize when unset.
func (c Client) GetQueueComplete(ctx context.Context, options GetQueueOperationOptions) (result GetQueueCompleteResult, err error) {
	if options.PageSize <= 0 {
		options.PageSize = client.DefaultPageSize
	}
	if options.Page <= 0 {
		options.Page = 1
	}
	for {
		var page GetQueueOperationResponse
		page, err = c.GetQueue(ctx, options)
		result.LatestHttpResponse = page.HttpResponse
		if err != nil {
			err = fmt.Errorf("loading results: %w", err)
			return
		}
		if page.Model == nil || len(page.Model.Records) == 0 {
			return
		}
		result.Items = append(result.Items, page.Model.Records...)
		// a short page is the last; so is the page that reaches the total
		if len(page.Model.Records) < options.PageSize || page.Model.TotalRecords > 0 && options.Page*options.PageSize >= page.Model.TotalRecords {
			return
		}
		options.Page++
	}
}
