// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetQueueDetailsOperationResponse is the result of GetQueueDetails.
type GetQueueDetailsOperationResponse struct {
	HttpResponse *http.Response
	Model        []QueueResource
}

// GetQueueDetailsOperationOptions holds the query and header parameters of GetQueueDetails.
type GetQueueDetailsOperationOptions struct {
	SeriesId       int
	EpisodeIds     []int
	IncludeSeries  *bool
	IncludeEpisode *bool
}

// ToHeaders returns the header parameters the options set.
func (o GetQueueDetailsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetQueueDetailsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.SeriesId != 0 {
		out.Append("seriesId", strconv.Itoa(o.SeriesId))
	}
	for _, v := range o.EpisodeIds {
		out.Append("episodeIds", strconv.Itoa(v))
	}
	if o.IncludeSeries != nil {
		out.Append("includeSeries", strconv.FormatBool(*o.IncludeSeries))
	}
	if o.IncludeEpisode != nil {
		out.Append("includeEpisode", strconv.FormatBool(*o.IncludeEpisode))
	}
	return &out
}

// GetQueueDetails calls GET /api/v3/queue/details.
func (c Client) GetQueueDetails(ctx context.Context, options GetQueueDetailsOperationOptions) (result GetQueueDetailsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/queue/details",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
