// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// DeleteQueueByIdOperationResponse is the result of DeleteQueueById.
type DeleteQueueByIdOperationResponse struct {
	HttpResponse *http.Response
}

// DeleteQueueByIdOperationOptions holds the query and header parameters of DeleteQueueById.
type DeleteQueueByIdOperationOptions struct {
	RemoveFromClient *bool
	Blocklist        *bool
	SkipRedownload   *bool
	ChangeCategory   *bool
}

// ToHeaders returns the header parameters the options set.
func (o DeleteQueueByIdOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o DeleteQueueByIdOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.RemoveFromClient != nil {
		out.Append("removeFromClient", strconv.FormatBool(*o.RemoveFromClient))
	}
	if o.Blocklist != nil {
		out.Append("blocklist", strconv.FormatBool(*o.Blocklist))
	}
	if o.SkipRedownload != nil {
		out.Append("skipRedownload", strconv.FormatBool(*o.SkipRedownload))
	}
	if o.ChangeCategory != nil {
		out.Append("changeCategory", strconv.FormatBool(*o.ChangeCategory))
	}
	return &out
}

// DeleteQueueById calls DELETE /api/v3/queue/{id}.
func (c Client) DeleteQueueById(ctx context.Context, id int, options DeleteQueueByIdOperationOptions) (result DeleteQueueByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodDelete,
		OptionsObject: options,
		Path:          fmt.Sprintf("/api/v3/queue/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
