// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PostReleaseProfileOperationResponse is the result of PostReleaseProfile.
type PostReleaseProfileOperationResponse struct {
	HttpResponse *http.Response
	Model        *ReleaseProfileResource
}

// PostReleaseProfile calls POST /api/v3/releaseprofile.
func (c Client) PostReleaseProfile(ctx context.Context, input ReleaseProfileResource) (result PostReleaseProfileOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusCreated,
		},
		HttpMethod: http.MethodPost,
		Path:       "/api/v3/releaseprofile",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model ReleaseProfileResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
