// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// ReleaseProfileResource is the "ReleaseProfileResource" schema.
type ReleaseProfileResource struct {
	Enabled   *bool  `json:"enabled,omitempty"`
	Id        int    `json:"id,omitempty"`
	Ignored   any    `json:"ignored,omitempty"`
	IndexerId int    `json:"indexerId,omitempty"`
	Name      string `json:"name,omitempty"`
	Required  any    `json:"required,omitempty"`
	Tags      []int  `json:"tags,omitzero"`
}
