// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetReleaseProfileByIdOperationResponse is the result of GetReleaseProfileById.
type GetReleaseProfileByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *ReleaseProfileResource
}

// GetReleaseProfileById calls GET /api/v3/releaseprofile/{id}.
func (c Client) GetReleaseProfileById(ctx context.Context, id int) (result GetReleaseProfileByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/api/v3/releaseprofile/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model ReleaseProfileResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
