// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PostRemotePathMappingOperationResponse is the result of PostRemotePathMapping.
type PostRemotePathMappingOperationResponse struct {
	HttpResponse *http.Response
	Model        *RemotePathMappingResource
}

// PostRemotePathMapping calls POST /api/v3/remotepathmapping.
func (c Client) PostRemotePathMapping(ctx context.Context, input RemotePathMappingResource) (result PostRemotePathMappingOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusCreated,
		},
		HttpMethod: http.MethodPost,
		Path:       "/api/v3/remotepathmapping",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model RemotePathMappingResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
