// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetRemotePathMappingOperationResponse is the result of GetRemotePathMapping.
type GetRemotePathMappingOperationResponse struct {
	HttpResponse *http.Response
	Model        []RemotePathMappingResource
}

// GetRemotePathMapping calls GET /api/v3/remotepathmapping.
func (c Client) GetRemotePathMapping(ctx context.Context) (result GetRemotePathMappingOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/remotepathmapping",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
