// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// RemotePathMappingResource is the "RemotePathMappingResource" schema.
type RemotePathMappingResource struct {
	Host       string `json:"host,omitempty"`
	Id         int    `json:"id,omitempty"`
	LocalPath  string `json:"localPath,omitempty"`
	RemotePath string `json:"remotePath,omitempty"`
}
