// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetRenameOperationResponse is the result of GetRename.
type GetRenameOperationResponse struct {
	HttpResponse *http.Response
	Model        []RenameEpisodeResource
}

// GetRenameOperationOptions holds the query and header parameters of GetRename.
type GetRenameOperationOptions struct {
	SeriesId     int
	SeasonNumber int
}

// ToHeaders returns the header parameters the options set.
func (o GetRenameOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetRenameOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.SeriesId != 0 {
		out.Append("seriesId", strconv.Itoa(o.SeriesId))
	}
	if o.SeasonNumber != 0 {
		out.Append("seasonNumber", strconv.Itoa(o.SeasonNumber))
	}
	return &out
}

// GetRename calls GET /api/v3/rename.
func (c Client) GetRename(ctx context.Context, options GetRenameOperationOptions) (result GetRenameOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/rename",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
