// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// UnmappedFolder is the "UnmappedFolder" schema.
type UnmappedFolder struct {
	Name         string `json:"name,omitempty"`
	Path         string `json:"path,omitempty"`
	RelativePath string `json:"relativePath,omitempty"`
}
