// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// RootFolderResource is the "RootFolderResource" schema.
type RootFolderResource struct {
	Accessible      *bool            `json:"accessible,omitempty"`
	FreeSpace       int64            `json:"freeSpace,omitempty"`
	Id              int              `json:"id,omitempty"`
	Path            string           `json:"path,omitempty"`
	UnmappedFolders []UnmappedFolder `json:"unmappedFolders,omitzero"`
}
