// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// MonitoringOptions is the "MonitoringOptions" schema.
type MonitoringOptions struct {
	IgnoreEpisodesWithFiles    *bool        `json:"ignoreEpisodesWithFiles,omitempty"`
	IgnoreEpisodesWithoutFiles *bool        `json:"ignoreEpisodesWithoutFiles,omitempty"`
	Monitor                    MonitorTypes `json:"monitor,omitempty"`
}
