// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// SeasonPassResource is the "SeasonPassResource" schema.
type SeasonPassResource struct {
	MonitoringOptions *MonitoringOptions         `json:"monitoringOptions,omitempty"`
	Series            []SeasonPassSeriesResource `json:"series,omitzero"`
}
