// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// SeasonPassSeriesResource is the "SeasonPassSeriesResource" schema.
type SeasonPassSeriesResource struct {
	Id        int              `json:"id,omitempty"`
	Monitored *bool            `json:"monitored,omitempty"`
	Seasons   []SeasonResource `json:"seasons,omitzero"`
}
