// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PostSeasonPassOperationResponse is the result of PostSeasonPass.
type PostSeasonPassOperationResponse struct {
	HttpResponse *http.Response
}

// PostSeasonPass calls POST /api/v3/seasonpass.
func (c Client) PostSeasonPass(ctx context.Context, input SeasonPassResource) (result PostSeasonPassOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusAccepted,
		},
		HttpMethod: http.MethodPost,
		Path:       "/api/v3/seasonpass",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
