// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PutSeriesByIdOperationResponse is the result of PutSeriesById.
type PutSeriesByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *SeriesResource
}

// PutSeriesByIdOperationOptions holds the query and header parameters of PutSeriesById.
type PutSeriesByIdOperationOptions struct {
	MoveFiles *bool
}

// ToHeaders returns the header parameters the options set.
func (o PutSeriesByIdOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PutSeriesByIdOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.MoveFiles != nil {
		out.Append("moveFiles", strconv.FormatBool(*o.MoveFiles))
	}
	return &out
}

// PutSeriesById calls PUT /api/v3/series/{id}.
func (c Client) PutSeriesById(ctx context.Context, id string, input SeriesResource, options PutSeriesByIdOperationOptions) (result PutSeriesByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusAccepted,
		},
		HttpMethod:    http.MethodPut,
		OptionsObject: options,
		Path:          fmt.Sprintf("/api/v3/series/%s", url.PathEscape(id)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model SeriesResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
