// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// SeriesEditorResource is the "SeriesEditorResource" schema.
type SeriesEditorResource struct {
	AddImportListExclusion *bool               `json:"addImportListExclusion,omitempty"`
	ApplyTags              ApplyTags           `json:"applyTags,omitempty"`
	DeleteFiles            *bool               `json:"deleteFiles,omitempty"`
	MonitorNewItems        NewItemMonitorTypes `json:"monitorNewItems,omitempty"`
	Monitored              *bool               `json:"monitored,omitempty"`
	MoveFiles              *bool               `json:"moveFiles,omitempty"`
	QualityProfileId       int                 `json:"qualityProfileId,omitempty"`
	RootFolderPath         string              `json:"rootFolderPath,omitempty"`
	SeasonFolder           *bool               `json:"seasonFolder,omitempty"`
	SeriesIds              []int               `json:"seriesIds,omitzero"`
	SeriesType             SeriesTypes         `json:"seriesType,omitempty"`
	Tags                   []int               `json:"tags,omitzero"`
}
