// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// DeleteSeriesByIdOperationResponse is the result of DeleteSeriesById.
type DeleteSeriesByIdOperationResponse struct {
	HttpResponse *http.Response
}

// DeleteSeriesByIdOperationOptions holds the query and header parameters of DeleteSeriesById.
type DeleteSeriesByIdOperationOptions struct {
	DeleteFiles            *bool
	AddImportListExclusion *bool
}

// ToHeaders returns the header parameters the options set.
func (o DeleteSeriesByIdOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o DeleteSeriesByIdOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.DeleteFiles != nil {
		out.Append("deleteFiles", strconv.FormatBool(*o.DeleteFiles))
	}
	if o.AddImportListExclusion != nil {
		out.Append("addImportListExclusion", strconv.FormatBool(*o.AddImportListExclusion))
	}
	return &out
}

// DeleteSeriesById calls DELETE /api/v3/series/{id}.
func (c Client) DeleteSeriesById(ctx context.Context, id int, options DeleteSeriesByIdOperationOptions) (result DeleteSeriesByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodDelete,
		OptionsObject: options,
		Path:          fmt.Sprintf("/api/v3/series/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
