// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"net/http"
	"testing"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

func TestOperationDeleteSeriesById(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 200, "", "")
	result, err := c.DeleteSeriesById(t.Context(), 7, DeleteSeriesByIdOperationOptions{
		DeleteFiles:            new(true),
		AddImportListExclusion: new(true),
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodDelete, "/api/v3/series/7")
	expectQuery(t, r, "deleteFiles", "true")
	expectQuery(t, r, "addImportListExclusion", "true")
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 200 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.DeleteSeriesById(t.Context(), 7, DeleteSeriesByIdOperationOptions{
		DeleteFiles:            new(true),
		AddImportListExclusion: new(true),
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
