// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// DeleteSeriesEditorOperationResponse is the result of DeleteSeriesEditor.
type DeleteSeriesEditorOperationResponse struct {
	HttpResponse *http.Response
}

// DeleteSeriesEditor calls DELETE /api/v3/series/editor.
func (c Client) DeleteSeriesEditor(ctx context.Context, input SeriesEditorResource) (result DeleteSeriesEditorOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodDelete,
		Path:       "/api/v3/series/editor",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
