// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetSeriesOperationResponse is the result of GetSeries.
type GetSeriesOperationResponse struct {
	HttpResponse *http.Response
	Model        []SeriesResource
}

// GetSeriesOperationOptions holds the query and header parameters of GetSeries.
type GetSeriesOperationOptions struct {
	TvdbId              int
	IncludeSeasonImages *bool
}

// ToHeaders returns the header parameters the options set.
func (o GetSeriesOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetSeriesOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.TvdbId != 0 {
		out.Append("tvdbId", strconv.Itoa(o.TvdbId))
	}
	if o.IncludeSeasonImages != nil {
		out.Append("includeSeasonImages", strconv.FormatBool(*o.IncludeSeasonImages))
	}
	return &out
}

// GetSeries calls GET /api/v3/series.
func (c Client) GetSeries(ctx context.Context, options GetSeriesOperationOptions) (result GetSeriesOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/series",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
