// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetSeriesByIdOperationResponse is the result of GetSeriesById.
type GetSeriesByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *SeriesResource
}

// GetSeriesByIdOperationOptions holds the query and header parameters of GetSeriesById.
type GetSeriesByIdOperationOptions struct {
	IncludeSeasonImages *bool
}

// ToHeaders returns the header parameters the options set.
func (o GetSeriesByIdOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetSeriesByIdOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.IncludeSeasonImages != nil {
		out.Append("includeSeasonImages", strconv.FormatBool(*o.IncludeSeasonImages))
	}
	return &out
}

// GetSeriesById calls GET /api/v3/series/{id}.
func (c Client) GetSeriesById(ctx context.Context, id int, options GetSeriesByIdOperationOptions) (result GetSeriesByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          fmt.Sprintf("/api/v3/series/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model SeriesResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
