// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetSeriesLookupOperationResponse is the result of GetSeriesLookup.
type GetSeriesLookupOperationResponse struct {
	HttpResponse *http.Response
	Model        []SeriesResource
}

// GetSeriesLookupOperationOptions holds the query and header parameters of GetSeriesLookup.
type GetSeriesLookupOperationOptions struct {
	Term string
}

// ToHeaders returns the header parameters the options set.
func (o GetSeriesLookupOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetSeriesLookupOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Term != "" {
		out.Append("term", o.Term)
	}
	return &out
}

// GetSeriesLookup calls GET /api/v3/series/lookup.
func (c Client) GetSeriesLookup(ctx context.Context, options GetSeriesLookupOperationOptions) (result GetSeriesLookupOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/series/lookup",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
