// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PutSeriesEditorOperationResponse is the result of PutSeriesEditor.
type PutSeriesEditorOperationResponse struct {
	HttpResponse *http.Response
	Model        []SeriesResource
}

// PutSeriesEditor calls PUT /api/v3/series/editor.
func (c Client) PutSeriesEditor(ctx context.Context, input SeriesEditorResource) (result PutSeriesEditorOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusAccepted,
		},
		HttpMethod: http.MethodPut,
		Path:       "/api/v3/series/editor",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
