// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetSeriesByIdFolderOperationResponse is the result of GetSeriesByIdFolder.
type GetSeriesByIdFolderOperationResponse struct {
	HttpResponse *http.Response
	Model        json.RawMessage
}

// GetSeriesByIdFolder calls GET /api/v3/series/{id}/folder.
func (c Client) GetSeriesByIdFolder(ctx context.Context, id int) (result GetSeriesByIdFolderOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/api/v3/series/%d/folder", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
