// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// DatabaseType is the "DatabaseType" enum.
type DatabaseType string

// Values of DatabaseType.
const (
	DatabaseTypeSqLite     DatabaseType = "sqLite"
	DatabaseTypePostgreSQL DatabaseType = "postgreSQL"
)

// PossibleValuesForDatabaseType returns every value of DatabaseType.
func PossibleValuesForDatabaseType() []string {
	return []string{
		string(DatabaseTypeSqLite),
		string(DatabaseTypePostgreSQL),
	}
}

// RuntimeMode is the "RuntimeMode" enum.
type RuntimeMode string

// Values of RuntimeMode.
const (
	RuntimeModeConsole RuntimeMode = "console"
	RuntimeModeService RuntimeMode = "service"
	RuntimeModeTray    RuntimeMode = "tray"
)

// PossibleValuesForRuntimeMode returns every value of RuntimeMode.
func PossibleValuesForRuntimeMode() []string {
	return []string{
		string(RuntimeModeConsole),
		string(RuntimeModeService),
		string(RuntimeModeTray),
	}
}
