// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetSystemRoutesOperationResponse is the result of GetSystemRoutes.
//
// The operation answers text/plain, left unread in HttpResponse.Body, which
// the caller must close.
type GetSystemRoutesOperationResponse struct {
	HttpResponse *http.Response
}

// GetSystemRoutes calls GET /api/v3/system/routes.
func (c Client) GetSystemRoutes(ctx context.Context) (result GetSystemRoutesOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:     http.MethodGet,
		Path:           "/api/v3/system/routes",
		StreamResponse: true,
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
