// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// SystemResource is the "SystemResource" schema.
type SystemResource struct {
	AppData                       string             `json:"appData,omitempty"`
	AppName                       string             `json:"appName,omitempty"`
	Authentication                AuthenticationType `json:"authentication,omitempty"`
	Branch                        string             `json:"branch,omitempty"`
	BuildTime                     string             `json:"buildTime,omitempty"`
	DatabaseType                  DatabaseType       `json:"databaseType,omitempty"`
	DatabaseVersion               string             `json:"databaseVersion,omitempty"`
	InstanceName                  string             `json:"instanceName,omitempty"`
	IsAdmin                       *bool              `json:"isAdmin,omitempty"`
	IsDebug                       *bool              `json:"isDebug,omitempty"`
	IsDocker                      *bool              `json:"isDocker,omitempty"`
	IsLinux                       *bool              `json:"isLinux,omitempty"`
	IsNetCore                     *bool              `json:"isNetCore,omitempty"`
	IsOsx                         *bool              `json:"isOsx,omitempty"`
	IsProduction                  *bool              `json:"isProduction,omitempty"`
	IsUserInteractive             *bool              `json:"isUserInteractive,omitempty"`
	IsWindows                     *bool              `json:"isWindows,omitempty"`
	MigrationVersion              int                `json:"migrationVersion,omitempty"`
	Mode                          RuntimeMode        `json:"mode,omitempty"`
	OsName                        string             `json:"osName,omitempty"`
	OsVersion                     string             `json:"osVersion,omitempty"`
	PackageAuthor                 string             `json:"packageAuthor,omitempty"`
	PackageUpdateMechanism        UpdateMechanism    `json:"packageUpdateMechanism,omitempty"`
	PackageUpdateMechanismMessage string             `json:"packageUpdateMechanismMessage,omitempty"`
	PackageVersion                string             `json:"packageVersion,omitempty"`
	RuntimeName                   string             `json:"runtimeName,omitempty"`
	RuntimeVersion                string             `json:"runtimeVersion,omitempty"`
	SqliteVersion                 string             `json:"sqliteVersion,omitempty"`
	StartTime                     string             `json:"startTime,omitempty"`
	StartupPath                   string             `json:"startupPath,omitempty"`
	UrlBase                       string             `json:"urlBase,omitempty"`
	Version                       string             `json:"version,omitempty"`
}
