// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetSystemRoutesDuplicateOperationResponse is the result of GetSystemRoutesDuplicate.
type GetSystemRoutesDuplicateOperationResponse struct {
	HttpResponse *http.Response
	Model        json.RawMessage
}

// GetSystemRoutesDuplicate calls GET /api/v3/system/routes/duplicate.
func (c Client) GetSystemRoutesDuplicate(ctx context.Context) (result GetSystemRoutesDuplicateOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/system/routes/duplicate",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
