// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PostSystemShutdownOperationResponse is the result of PostSystemShutdown.
type PostSystemShutdownOperationResponse struct {
	HttpResponse *http.Response
}

// PostSystemShutdown calls POST /api/v3/system/shutdown.
func (c Client) PostSystemShutdown(ctx context.Context) (result PostSystemShutdownOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodPost,
		Path:       "/api/v3/system/shutdown",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
