// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// PostSystemRestartOperationResponse is the result of PostSystemRestart.
type PostSystemRestartOperationResponse struct {
	HttpResponse *http.Response
}

// PostSystemRestart calls POST /api/v3/system/restart.
func (c Client) PostSystemRestart(ctx context.Context) (result PostSystemRestartOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodPost,
		Path:       "/api/v3/system/restart",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
