// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetTagDetailByIdOperationResponse is the result of GetTagDetailById.
type GetTagDetailByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *TagDetailsResource
}

// GetTagDetailById calls GET /api/v3/tag/detail/{id}.
func (c Client) GetTagDetailById(ctx context.Context, id int) (result GetTagDetailByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/api/v3/tag/detail/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model TagDetailsResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
