// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// TaskResource is the "TaskResource" schema.
type TaskResource struct {
	Id            int    `json:"id,omitempty"`
	Interval      int    `json:"interval,omitempty"`
	LastDuration  string `json:"lastDuration,omitempty"`
	LastExecution string `json:"lastExecution,omitempty"`
	LastStartTime string `json:"lastStartTime,omitempty"`
	Name          string `json:"name,omitempty"`
	NextExecution string `json:"nextExecution,omitempty"`
	TaskName      string `json:"taskName,omitempty"`
}
