// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// UiConfigResource is the "UiConfigResource" schema.
type UiConfigResource struct {
	CalendarWeekColumnHeader string `json:"calendarWeekColumnHeader,omitempty"`
	EnableColorImpairedMode  *bool  `json:"enableColorImpairedMode,omitempty"`
	FirstDayOfWeek           int    `json:"firstDayOfWeek,omitempty"`
	Id                       int    `json:"id,omitempty"`
	LongDateFormat           string `json:"longDateFormat,omitempty"`
	ShortDateFormat          string `json:"shortDateFormat,omitempty"`
	ShowRelativeDates        *bool  `json:"showRelativeDates,omitempty"`
	Theme                    string `json:"theme,omitempty"`
	TimeFormat               string `json:"timeFormat,omitempty"`
	UiLanguage               int    `json:"uiLanguage,omitempty"`
}
