// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// UiConfigResource is the "UiConfigResource" schema.
type UiConfigResource struct {
	CalendarWeekColumnHeader string `json:"calendarWeekColumnHeader"`
	EnableColorImpairedMode  *bool  `json:"enableColorImpairedMode,omitempty"`
	FirstDayOfWeek           int    `json:"firstDayOfWeek"`
	Id                       int    `json:"id"`
	LongDateFormat           string `json:"longDateFormat"`
	ShortDateFormat          string `json:"shortDateFormat"`
	ShowRelativeDates        *bool  `json:"showRelativeDates,omitempty"`
	Theme                    string `json:"theme"`
	TimeFormat               string `json:"timeFormat"`
	UiLanguage               int    `json:"uiLanguage"`
}
