// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// UpdateChanges is the "UpdateChanges" schema.
type UpdateChanges struct {
	Fixed []string `json:"fixed,omitzero"`
	New   []string `json:"new,omitzero"`
}
