// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

// UpdateResource is the "UpdateResource" schema.
type UpdateResource struct {
	Branch      string         `json:"branch,omitempty"`
	Changes     *UpdateChanges `json:"changes,omitempty"`
	FileName    string         `json:"fileName,omitempty"`
	Hash        string         `json:"hash,omitempty"`
	Id          int            `json:"id,omitempty"`
	Installable *bool          `json:"installable,omitempty"`
	Installed   *bool          `json:"installed,omitempty"`
	InstalledOn string         `json:"installedOn,omitempty"`
	Latest      *bool          `json:"latest,omitempty"`
	ReleaseDate string         `json:"releaseDate,omitempty"`
	Url         string         `json:"url,omitempty"`
	Version     string         `json:"version,omitempty"`
}
