// Code generated by internal/pandorest; DO NOT EDIT.

package sonarr

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/sonarr-mcp/lib/client"
)

// GetLogFileUpdateByFilenameOperationResponse is the result of GetLogFileUpdateByFilename.
//
// The operation answers text/plain, left unread in HttpResponse.Body, which
// the caller must close.
type GetLogFileUpdateByFilenameOperationResponse struct {
	HttpResponse *http.Response
}

// GetLogFileUpdateByFilename calls GET /api/v3/log/file/update/{filename}.
func (c Client) GetLogFileUpdateByFilename(ctx context.Context, filename string) (result GetLogFileUpdateByFilenameOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:     http.MethodGet,
		Path:           fmt.Sprintf("/api/v3/log/file/update/%s", url.PathEscape(filename)),
		StreamResponse: true,
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
